### ISSUE TITLE
可以扩展一个方法 删除任务并删除下载完成的缓存

### ISSUE THREAD

**Issue by Shirley0202** [Danie1s/Tiercel#1]
现在的 remove 只是删除了任务 并没有清除这个下载的缓存. 需要彻底的删除,谢谢

**Comment by Danie1s** [comment]
remove方法是把下载任务清除，如果这个任务并没有完成，那么就会把没有下载完成的文件删除，下载完成的文件保留，因为我考虑到这是在移动端，所以尽可能地节省用户的流量。如果你实在是想把下载完成的文件也移除，可以使用`guard let downloadFile = cache.filePtah(URLString) else { return }`获得文件路径，再使用fileManager进行删除，如果有什么疑问，欢迎提出，谢谢

**Comment by Danie1s** [comment]
我后来觉得也是有必要增加这么一个方法，所以现在已经更新了

**Comment by Shirley0202** [comment]
这个下载器在你的项目中有用到吗?

**Comment by Danie1s** [comment]
@Shirley0202 有的

**Comment by Shirley0202** [comment]
那再给你提一个bug 你的最大并发数如果设置了2,同时添加10  如果前两个没有下载完成 关闭程序 你只保存了2个, 你的保存时机是在 下载开始的时候, 这样都丢了8个,

**Comment by Danie1s** [comment]
谢谢你的提交，已经修复。
下载任务超过最大并发数而导致某些任务没开始下载，这种情况下进行全局的操作，确实存在不少问题，目前仍在努力解决中，解决后会一起更新。

**Comment by ZClee128** [comment]
> 我后来觉得也是有必要增加这么一个方法，所以现在已经更新了

是调用哪个方法呢

**Comment by Danie1s** [comment]
> > 我后来觉得也是有必要增加这么一个方法，所以现在已经更新了
> 
> 是调用哪个方法呢


SessionManager.remove(_:completely:onMainQueue:handler:)
