### ISSUE TITLE
手动集成会报错

### ISSUE THREAD

**Issue by zhangdongpo** [Danie1s/Tiercel#10]
![image](https://user-images.githubusercontent.com/15242207/41149830-252a7ef2-6b3f-11e8-809d-495552bbd0cd.png)

**Comment by Danie1s** [comment]
我放进去一个空白的项目，没有问题。不保证可以和OC混编

**Comment by zhangdongpo** [comment]
@Danie1s 混编报错

**Comment by zhangdongpo** [comment]
我pod了几个东西就有问题了，不知道是啥问题

**Comment by zhangdongpo** [comment]
pod 'Moya', '~> 11.0'
  pod 'Kingfisher'
  pod 'HandyJSON', '~> 4.1.0'
  pod 'MJRefresh'
  pod 'SnapKit', '~> 4.0.0'
  pod 'DTCoreText'
  pod 'FSPagerView'
  pod 'SwiftyRSA', 
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'SwiftyUserDefaults'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'


这是我pod的，你可以pod一下试试，然后再混编一下

**Comment by sunnyhigher** [comment]
将桥接文件中 RxSwift 的头文件注释就可以解决这个问题，冲突引起的 @zhangdongpo
