### ISSUE TITLE
请问在AppDelegate创建下载目录后，是否还可以更改

### ISSUE THREAD

**Issue by yangwei0401** [Danie1s/Tiercel#100]
需求是因为要下载的文件，想存在不同的目录下，而SessionManager要在AppDelegate创建，而后SessionManager的Cache是 Let熟悉，它的downloadPath等三个路径也是let不能更改的属性。
我如何才能在下载完一个文件后，变更这个下载路径呢？

谢谢

**Comment by Danie1s** [comment]
你下载完了以后，直接移动文件就可以了
