### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by MrKang** [Danie1s/Tiercel#102]
我不知道是不是我代码看的不仔细，或者是自己的swift功力太低。
1.目前好像没办法把一个downloadTask和app内的其他信息做关联，比如我下载个文件，这文件有很多其他属性，但是目前task并没有一个类似tagId之类的东西当个key来跟外部关联。
2.关于文件名。一个资料下载的时候目前只能是：
1）自己指定名字
2）默认对URL进行md5
但是，有的下载时其实名字是在header里的，这个好像目前没法儿在下载时作处理？

如果是我用法不对，或者对swift以及iOS开发不够了解的话，那打扰了……

**Comment by Danie1s** [comment]
1. 用 URL 作为 task 的唯一标识
2. 你想用 `suggestedFilename` ？获得这个信息的前提是已经进行了请求，这会影响整个框架的实现，所以我没有这样做，你可以下载完成后改成 `suggestedFilename`
