### ISSUE TITLE
如果我想在urlSession:didReceive:completionHandler: 处理

### ISSUE THREAD

**Issue by nicaho** [Danie1s/Tiercel#105]
The certificate for this server is invalid. You might be connecting to a server that is pretending to be

**Comment by nicaho** [comment]
由于服务器的原因，需要处理The certificate for this server is invalid. You might be connecting to a server that is pretending to be这种问题，就需要在URLSessionDownloadDelegate的   urlSession:didReceive:completionHandler:信任证书才行。请问在贵框架里，应该怎么实现呢

**Comment by Danie1s** [comment]
不好意思，暂时没有提供相关的接口，可能下个版本会增加

**Comment by nicaho** [comment]
好的，期待。谢谢你
