### ISSUE TITLE
iOS13，视频下载成功了，但是文件却不存在，无法播放（重签名后）

### ISSUE THREAD

**Issue by qxc122** [Danie1s/Tiercel#106]
iOS13，视频下载成功了，但是文件却不存在，（只是在ipa包重签名后会出现这种情况，不重签名是正常的，DEBUG模式也是正常的，不知道有人遇到这种情况没），求作者分析下可能是什么问题，我已经把视频保存位置改到 Docment了。（使用的是企业证书重签名的）

**Comment by qxc122** [comment]
我的pod 文件这么写的，应该和作者的demo版本不一样
platform :ios, '8.0'
pod 'Tiercel'

**Comment by Danie1s** [comment]
一般重签名会把 `bundle id` 也改了，Tiercel的缓存跟  `bundle id`  相关，你尝试看看文件的路径有没有问题吧

**Comment by qxc122** [comment]
Tiercel的缓存跟 bundle id 没有相关吧，框架中只看到SessionManager文件中
    public init(_ identifier: String,
                configuration: SessionConfiguration,
                operationQueue: DispatchQueue = DispatchQueue(label: "com.Tiercel.SessionManager.operationQueue")) {
        let bundleIdentifier = Bundle.main.bundleIdentifier ?? "com.Daniels.Tiercel"
        self.identifier = "\(bundleIdentifier).\(identifier)"
框架中只看到SessionManager文件跟 bundle id 相关啊，
是不是

**Comment by Danie1s** [comment]
不好意思，我搞错了。这个问题我没有收到其他人的反馈，一般重签名只会影响 `bundle id` ，你要先保证下载成功，然后再调试一下保存的目录有没有出错

**Comment by qxc122** [comment]
背景：（企业重签名，不修改bundle id的方式《如果以修改bundle id的方式重签名，就正常》）
我改了下TiercelLog函数，把logo 写到沙河里了，下面是一段logo 日志，说没有权限移动文件，，能帮看下吗，，，

Source     :  downVedio.swift[23]
Thread     :  number = 1
identifier :  111
Info       :  kaishiSource     :  SessionManager.swift[236]
Thread     :  number = 1
identifier :  com.shuiguo.app.shuiGuo
Info       :  [manager] retrieveTasks, tasks.count: 0Source     :  DownloadTask.swift[245]
Thread     :  number = 19
identifier :  com.shuiguo.app.shuiGuo
url        :  http://znzj3.xyz/uploads/mp4/a/2020/04/09/202004090003135762/20200409000313576290999.mp4
Info       :  [downloadTask] runningSource     :  SessionManager.swift[528]
Thread     :  number = 19
identifier :  com.shuiguo.app.shuiGuo
Info       :  [manager] runningSource     :  Cache.swift[243]
Thread     :  number = 21
identifier :  shuiGuo
Info       :  moveItem error: Error Domain=NSCocoaErrorDomain Code=513 "“CFNetworkDownload_I9HHIa.tmp” couldn’t be moved because you don’t have permission to access “File”." UserInfo={NSSourceFilePathErrorKey=/private/var/mobile/Containers/Data/Application/ADF58A39-24DC-4D78-83BC-283615B7DD61/Library/Caches/com.apple.nsurlsessiond/Downloads/com.git.forme/CFNetworkDownload_I9HHIa.tmp, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/var/mobile/Containers/Data/Application/C3EFE2DF-7424-4603-9DB5-D0353EAFAD09/Documents/com.Daniels.Tiercel.Cache.shuiGuo/Downloads/File/8c88866ad97f8cbb1b92c3e961ec3f28.mp4, NSFilePath=/private/var/mobile/Containers/Data/Application/ADF58A39-24DC-4D78-83BC-283615B7DD61/Library/Caches/com.apple.nsurlsessiond/Downloads/com.git.forme/CFNetworkDownload_I9HHIa.tmp, NSUnderlyingError=0x283f16850 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}Source     :  DownloadTask.swift[361]
Thread     :  number = 21
identifier :  com.shuiguo.app.shuiGuo
url        :  http://znzj3.xyz/uploads/mp4/a/2020/04/09/202004090003135762/20200409000313576290999.mp4
Info       :  [downloadTask] completedSource     :  SessionManager.swift[607]
Thread     :  number = 21
identifier :  com.shuiguo.app.shuiGuo
Info       :  [manager] succeededSource     :  DownloadTask.swift[297]
Thread     :  number = 21
identifier :  com.shuiguo.app.shuiGuo
url        :  http://znzj3.xyz/uploads/mp4/a/2020/04/09/202004090003135762/20200409000313576290999.mp4
Info       :  [downloadTask] did removeSource     :  SessionManager.swift[577]
Thread     :  number = 21
identifier :  com.shuiguo.app.shuiGuo
Info       :  [manager] removedSource     :  DownloadTask.swift[245]
Thread     :  number = 21
identifier :  com.shuiguo.app.shuiGuo
url        :  http://znzj3.xyz/uploads/mp4/a/2020/04/09/202004090003135762/20200409000313576290999.mp4
Info       :  [downloadTask] runningSource     :  SessionManager.swift[528]
Thread     :  number = 21
identifier :  com.shuiguo.app.shuiGuo
Info       :  [manager] runningSource     :  Cache.swift[243]
Thread     :  number = 25
identifier :  shuiGuo
Info       :  moveItem error: Error Domain=NSCocoaErrorDomain Code=513 "“CFNetworkDownload_Dnqzib.tmp” couldn’t be moved because you don’t have permission to access “File”." UserInfo={NSSourceFilePathErrorKey=/private/var/mobile/Containers/Data/Application/ADF58A39-24DC-4D78-83BC-283615B7DD61/Library/Caches/com.apple.nsurlsessiond/Downloads/com.git.forme/CFNetworkDownload_Dnqzib.tmp, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/var/mobile/Containers/Data/Application/C3EFE2DF-7424-4603-9DB5-D0353EAFAD09/Documents/com.Daniels.Tiercel.Cache.shuiGuo/Downloads/File/8c88866ad97f8cbb1b92c3e961ec3f28.mp4, NSFilePath=/private/var/mobile/Containers/Data/Application/ADF58A39-24DC-4D78-83BC-283615B7DD61/Library/Caches/com.apple.nsurlsessiond/Downloads/com.git.forme/CFNetworkDownload_Dnqzib.tmp, NSUnderlyingError=0x283ff1ef0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}Source     :  DownloadTask.swift[361]
Thread     :  number = 25
identifier :  com.shuiguo.app.shuiGuo
url        :  http://znzj3.xyz/uploads/mp4/a/2020/04/09/202004090003135762/20200409000313576290999.mp4
Info       :  [downloadTask] completedSource     :  SessionManager.swift[607]
Thread     :  number = 25
identifier :  com.shuiguo.app.shuiGuo
Info       :  [manager] succeededSource     :  DownloadTask.swift[297]
Thread     :  number = 25
identifier :  com.shuiguo.app.shuiGuo
url        :  http://znzj3.xyz/uploads/mp4/a/2020/04/09/202004090003135762/20200409000313576290999.mp4
Info       :  [downloadTask] did removeSource     :  SessionManager.swift[577]
Thread     :  number = 25
identifier :  com.shuiguo.app.shuiGuo
Info       :  [manager] removedSource     :  DownloadTask.swift[245]
Thread     :  number = 25
identifier :  com.shuiguo.app.shuiGuo
url        :  http://znzj3.xyz/uploads/mp4/a/2020/04/09/202004090003135762/20200409000313576290999.mp4
Info       :  [downloadTask] runningSource     :  SessionManager.swift[528]
Thread     :  number = 25
identifier :  com.shuiguo.app.shuiGuo
Info       :  [manager] running

**Comment by qxc122** [comment]
背景：（企业重签名，不修改bundle id的方式《com.git.forme是我的新描述文件对应的bundle id》《如果以修改bundle id的方式重签名，就正常》）
我改了下TiercelLog函数，把logo 写到沙河里了，下面是一段logo 日志，
貌似不能解决，我尝试复制也不行，也是提示无权限
Info       :  111copyItem error: Error Domain=NSCocoaErrorDomain Code=257 "The file “CFNetworkDownload_5PkQxo.tmp” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/private/var/mobile/Containers/Data/Application/ADF58A39-24DC-4D78-83BC-283615B7DD61/Library/Caches/com.apple.nsurlsessiond/Downloads/com.git.forme/CFNetworkDownload_5PkQxo.tmp, NSUnderlyingError=0x2815c1890 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}Source     :  DownloadTask.swift[361]

**Comment by qxc122** [comment]
应该是重签名后，这个文件是属于新的bundleid,而我的info.plist 文件和新的bundleid对不上
有没有什么办法解决啊，能提示下思路不
    internal func didFinishDownloading(task: URLSessionDownloadTask, to location: URL) {
我看了下，就是这个回掉函数里，location地址，重签名后，无权限去访问，复制，移动都不行，

**Comment by Danie1s** [comment]
是不是你保存的位置有问题？你换个位置吧，比如：用默认的位置

**Comment by qxc122** [comment]
不是的，我最开始就是使用默认位置，我保存的位置没有问题呢
internal func didFinishDownloading(task: URLSessionDownloadTask, to location: URL) {
这个函数是下载成功的回调，源码里面是location 位置的文件移动到另一个位置，然后log日志是说没有权限
我是重签名的app(不改BundleID的签法)，要是改BundleId 就正常

**Comment by Danie1s** [comment]
那就是 `bundle id` 跟实际目录对应不上导致的。其实也很好理解，就等于你 A 应用无法把文件保存在 B 应用嘛

**Comment by danleechina** [comment]
我在开发和线上环境都遇到了 513 没有权限的问题。有啥想法吗？环境是 iOS13 .4，Xcode11.4

**Comment by Danie1s** [comment]
@danleechina 在 `demo` 上有出现问题？抱歉，我不知道你具体是怎么使用的，是不是也进行了重签名？

**Comment by danleechina** [comment]
没有重签名。我用 copyItem 也有问题。
![image](https://user-images.githubusercontent.com/6702864/79539216-72685780-80b8-11ea-97c9-739fe242e3f2.png)

**Comment by danleechina** [comment]
![image](https://user-images.githubusercontent.com/6702864/79539268-9461da00-80b8-11ea-8b82-87b882296cda.png)
这个是用 copy 时候的错误信息

**Comment by Danie1s** [comment]
大哥，你把我的源码改了，来问我问题，我怎么解答？

**Comment by danleechina** [comment]
![image](https://user-images.githubusercontent.com/6702864/79539967-ece5a700-80b9-11ea-969e-242a8d8d96c9.png)
demo 是成功的。这个是 demo 里面的 location 地址

**Comment by danleechina** [comment]
> 大哥，你把我的源码改了，来问我问题，我怎么解答？

![image](https://user-images.githubusercontent.com/6702864/79540317-8ca33500-80ba-11ea-91c2-20c9abb418c9.png)
不好意思，这个是你原始代码的情况

**Comment by Danie1s** [comment]
抱歉，其他人也没提出类似问题。如果 `demo` 也没问题的话，那只能请你自己检查项目代码

**Comment by danleechina** [comment]
> 抱歉，其他人也没提出类似问题。如果 `demo` 也没问题的话，那只能请你自己检查项目代码

有啥想法吗。感觉 `func urlSession(_ session: URLSession, downloadTask: URLSessionDownloadTask, didFinishDownloadingTo location: URL)` 这个代理方法返回的 location 地址有点问题，不像是 tmp 文件目录地址。我是否能指定这个下载到的文件目录地址？

**Comment by danleechina** [comment]
补充一下，在 iOS12 上面是成功的。不知道为什么 iOS13.4 我们自己的 app 内部这个 location 地址不对（不是 tmp 文件目录地址）

**Comment by danleechina** [comment]
感觉这个是个系统问题。我将 demo 中的 bundle id 改成我们公司 app 的 bundle id，location 对应的文件也不能访问。然后将我们公司的 app 的 bundle id 改成随意另一个，location 对应的文件就能访问。只在我们的测试机 iOS 13.4.1 上面有这个情况，试了 iOS 13.1、13.2 和 iOS 12 都没有这个问题。然后我将 

``` 
let sessionConfiguration = URLSessionConfiguration.background(withIdentifier: identifier)
```
改成 
``` 
let sessionConfiguration = URLSessionConfiguration.default
```

用公司的 bundle id，对应的 location 文件就能访问了。具体出现的 log 和上面这位朋友的一样。

**Comment by danleechina** [comment]
好吧，重启了手机，什么改动都没有，就可以了。返回的 location 地址是 tmp 目录的地址，可以访问。神奇

**Comment by qxc122** [comment]
@danleechina  你也是重签名的情况下吗

**Comment by qxc122** [comment]
那就是 bundle id 跟实际目录对应不上导致的。其实也很好理解，就等于你 A 应用无法把文件保存在 B 应用嘛 对的，貌似我这个无解，，

**Comment by qxc122** [comment]
找到了一个官方的https://forums.developer.apple.com/thread/73426，也是有人遇到这个问题，我就想在重签名，Bundle id 不一致的实际，这个问题怎么解决，能有办法吗，大佬
@Danie1s

**Comment by Danie1s** [comment]
@qxc122 不清楚

**Comment by Hanwp** [comment]
Mark, 同遇到这个问题

**Comment by helloworldsmart** [comment]
@qxc122 大佬找到有解嗎？ thank you

**Comment by meilbn** [comment]
我也遇到这个问题了，现在还是没有解决办法吗？

**Comment by WilsonScott** [comment]
> iOS13，视频下载成功了，但是文件却不存在，（只是在ipa包重签名后会出现这种情况，不重签名是正常的，DEBUG模式也是正常的，不知道有人遇到这种情况没），求作者分析下可能是什么问题，我已经把视频保存位置改到 Docment了。（使用的是企业证书重签名的）

have u solved it bro ?

**Comment by WilsonScott** [comment]
i think it is the iOS's bug, it occured only when the ipa resigned ,i solved by this 
<img width="898" alt="image" src="https://user-images.githubusercontent.com/33718297/228119562-17b53686-ef99-402c-bbc8-1aee0f234c7e.png">

**Comment by WilsonScott** [comment]
bug we cannot download files in background anymore - _ -

**Comment by aboluoa** [comment]
特意解决这个问题后来回答.
ipa重新企业签名后,如果出现这个问题,需要把ipa里面的Payload/xxx.app/info.plist 里面的Bundle identifier修改成,企业签名的 application-identifier,企业签名的 application-identifier需要在 Payload/xxx.app/embedded.mobileprovision 里面打开来看,里面的 application-identifier 就是了.application-identifier 的格式是 TeamID.xxx.xxx.xx  取后面的 xxx.xxx.xx为info.plist 里面的 Bundle identifier就行,然后重新签名.就行了.
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/7e14cc94-0ddc-4a42-9242-5147e30aaff9">

**Comment by ETmanwenhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢你联系我。我会尽快给您回复。

**Comment by Danie1s** [comment]
> [@Danie1s](https://github.com/Danie1s) 企业签或者个人签重签名后，包名如果不一致，确实会有这个问题，稳定复现。大佬能更新解决下吗？不然就需要手动下载源码按上面截图的地方在createSession方法内修改了

试试 [aboluoa](https://github.com/aboluoa) 的回复
