### ISSUE TITLE
关于本地读取的问题

### ISSUE THREAD

**Issue by JQHee** [Danie1s/Tiercel#11]
怎么通过下载链接获取上一次下载文件的状态和下载进度

**Comment by Danie1s** [comment]
如果manager没有销毁的情况下:
`let task = downloadManager.fetchTask(URLString)`
可以得到task

如果你指的是关闭app，或者manager销毁的情况：
manager初始化的时候，参数isStoreInfo需要设置为ture，此时就可以拿到对应的task
`let task = downloadManager.fetchTask(URLString)`
