### ISSUE TITLE
下载的文件文件名

### ISSUE THREAD

**Issue by tanpengsccd** [Danie1s/Tiercel#113]
下载后文件 文件路径 "/var/mobile/Containers/Data/Application/CC671DB4-8BE6-4CC2-B249-4E4F43B7206F/Library/Caches/com.Daniels.Tiercel.Cache.default/Downloads/File/5748295818de7c139db9988143a8403a"

没有获取到正确的的文件名。

希望能获取正确文件名。
根据已经提过的问题。
https://github.com/Danie1s/Tiercel/issues/84
建议 session.download 时添加 useSuggestFilename:Bool ,来尝试获取到响应时 修改 文件名。
建议在task 里添加只读属性，只有在task 有回调时产生

**Comment by tanpengsccd** [comment]
请问 现在有没有什么方式能获取到 suggestedFilename

**Comment by Danie1s** [comment]
DownloadTask 里面有个 response 属性，可以获取 suggestedFilename

至于为什么不直接使用 suggestedFilename 来对下载文件进行命名，那是因为：
1、方便在下载之前判断本地是否已经存在该文件
2、方便根据URL来获取文件
