### ISSUE TITLE
Info       :  [manager] running

### ISSUE THREAD

**Issue by zhengzhong5127** [Danie1s/Tiercel#114]
我开启一个下载任务，log提示running，网络正常，收不到任何下载成功或者失败的回调。
`***************TiercelLog****************
Source     :  DownloadTask.swift[245]
Thread     :  number = 65
url        :  **************
Info       :  [downloadTask] running`

***************TiercelLog****************
Source     :  SessionManager.swift[527]
Thread     :  number = 65
Info       :  [manager] running

有时候也能正常下载

**Comment by Danie1s** [comment]
麻烦你先用demo试试，如果还有问题，请给我你的url

**Comment by f513234428** [comment]
https://test-azure-community.obs.cn-south-1.myhuaweicloud.com/20210528140741%2F75d69922aef24812912ad259f01e8ec9.jpeg
这个文件在demo里面没有收到下载成功回调,跟上述问题一样,奇怪的是ViewController2中是能下载成功的,但是剩下3个会卡住,暂时排查不出问题,麻烦看下
