### ISSUE TITLE
Support for cell download in tableview

### ISSUE THREAD

**Issue by tangzzz-fan** [Danie1s/Tiercel#119]
Hi, Daniels, 
    I used the tool in my test project for file download each file cell item, but Tiercel cannot give a good support about it, can you give a detail demo on it?
    The common scenario is a file list to download, click the cell download button to download the each file, observer the progress view in each cell.
    I tried the way: get tasks.safeObject in tableView:willDisplayCell, but, the order is missed.
    Thanks a lot

**Comment by Danie1s** [comment]
see the demo

![image](https://user-images.githubusercontent.com/19432029/90209742-be38cc80-de1e-11ea-96e4-1c4adc7eab98.png)

**Comment by tangzzz-fan** [comment]
the demo used in ViewController2 need add download task first, then get task in session manager according of index path row. But in tableview cell download cases, all tasks have not been add to the session manager, getTask(indexpath.row) will return a wrong task.

**Comment by Danie1s** [comment]
>  getTask(indexpath.row) will return a wrong task

why?
I think your problem is easy to solve.
When you  click the cell download button, add download task and reload the tableView.

```swift
func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
    
    if let task = sessionManager.tasks.safeObject(at: indexPath.row) {
        // observer the progress
    } else {
        // do nothing
    }
}
```

**Comment by tangzzz-fan** [comment]
Have solved the issue, thanks.
