### ISSUE TITLE
扩展属性

### ISSUE THREAD

**Issue by leeCoding** [Danie1s/Tiercel#124]
请问下使用桥接到 oc 的文件，如何扩展属性，我尝试在桥接文件中增加代码，但是会出现找不到方法引发奔溃，如增加资源类别属性在 TRDownloadTask 这个类中，如果可以作者能否增加这个 category 属性，类似 endDate、speed、fileName... 方便使用

**Comment by Danie1s** [comment]
不好意思，Tiercel 不支持在 Objective-C 上使用

**Comment by leeCoding** [comment]
TiercelObjCBridge 我使用的是这个，作者能否在 TRDownloadTask 类中增加一个 category 标识资源类型，可以在传入下载链接时设置该值
