### ISSUE TITLE
Xcode beta5，tr报错

### ISSUE THREAD

**Issue by ETHANAIR** [Danie1s/Tiercel#13]
Swift 4，Cocoapods 集成环境下
> 'tr' is inaccessible due to 'internal' protection level

**Comment by Danie1s** [comment]
你指的是xcode 10吗？我的源码中`tr`是使用`public`修饰的
```
    public var tr: Tiercel<Self> {
        get { return Tiercel(self) }
    }
```

目前我使用xcode9是没有问题的，我看了xcode10和swift 4.2的更新，好像没涉及到相关的东西，请你再次尝试吧
