### ISSUE TITLE
清理缓存后 Task无法重新下载

### ISSUE THREAD

**Issue by lixiang1994** [Danie1s/Tiercel#130]
调用后
```
Download.listeningSentences.cache.clearDiskCache(onMainQueue: true) { (cache) in }
```

如果存在已完成的Task 通过`fetchTask(url)` 获取到 task 的 status 为 .succeeded
尝试过 remove(task)后 重新调用`start(task)` 无法重新下载.

**Comment by lixiang1994** [comment]
已解决 使用`totalRemove(completely: true, onMainQueue: true)`就好了

**Comment by Resoulte** [comment]
哥们儿不起作用啊还会加载缓存的索引列表，不去下载

**Comment by Resoulte** [comment]
> 已解决 使用`totalRemove(completely: true, onMainQueue: true)`就好了

哥们儿不起作用啊还会加载缓存的索引列表，不去下载

**Comment by Danie1s** [comment]
@Resoulte 你先用 demo 试试，看看是不是你自己代码的问题
