### ISSUE TITLE
关于点击暂停操作

### ISSUE THREAD

**Issue by deepindo** [Danie1s/Tiercel#132]
Demo中似乎用的旧版本，参数是task

public func suspend(_ task: DownloadTask, onMainQueue: Bool = true, handler: Handler<DownloadTask>? = nil) {
        operationQueue.async {
            task.suspend(onMainQueue: onMainQueue, handler: handler)
        }
}

新版本中
/// 暂停任务，会触发sessionDelegate的完成回调
    public func suspend(_ url: URLConvertible, onMainQueue: Bool = true, _ handler: Handler<DownloadTask>? = nil) {
        operationQueue.async {
            guard let task = self.fetchTask(url) else { return }
            task.suspend(onMainQueue: onMainQueue, handler)
        }
    }
    
这个应该怎么弄呢？

**Comment by Danie1s** [comment]
两个都可以使用，就是传入的参数不一样
