### ISSUE TITLE
下载时重复调用两次

### ISSUE THREAD

**Issue by q760440238** [Danie1s/Tiercel#138]
![image](https://user-images.githubusercontent.com/15276753/99618286-0558de00-2a5c-11eb-8727-99d979b3f21d.png)

**Comment by Danie1s** [comment]
你看看有没有其他地方有监听或者回调？我之前测试过是不会重复调用的

**Comment by overlookart** [comment]
我也遇到了这个问题

**Comment by Danie1s** [comment]
这并不是重复调用，而是不同的回调，一个是DownloadTask的，一个是SessionManager的
