### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by 350541732** [Danie1s/Tiercel#14]
打包出错：
Undefined symbols for architecture arm64:
  "protocol witness table for Swift.Int64 : Tiercel.TiercelCompatible in Tiercel", referenced from:
大神这个不支持arm64吗？

**Comment by Danie1s** [comment]
肯定支持的，我公司的项目一直都有用

**Comment by 350541732** [comment]
使用真机测试没有问题 但是打ipa包的时候出现了这个错误
