### ISSUE TITLE
下载时有时会出现在Wi-Fi状态不下载

### ISSUE THREAD

**Issue by leeCoding** [Danie1s/Tiercel#144]
测试发现有些下载链接在Wi-Fi状态下无法下载，但是在用手机热点可以正常下载，这个是测试下载链接 http://cc.enable-ets.com/microservice/storageservice/v1/files/download/2020/9/16/16/12/46/2b1ba8777b534b5084ba7a63e37952f6.mp4

**Comment by Danie1s** [comment]
我用模拟器试了好多次，是没问题的，你是不是用了代理？

**Comment by leeCoding** [comment]
你说的什么代理是什么意思

**Comment by Danie1s** [comment]
Wi-Fi 中的代理

**Comment by leeCoding** [comment]
这个倒没有，我测试的时候基本是把把出现这个问题

**Comment by leeCoding** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/12134648/112813483-d1985f80-90b0-11eb-93c8-1b1090859883.png">

**Comment by leeCoding** [comment]
我观察的情况是，加入下载之后，很久不开始下载显示在下载中但是没进度，然后过了很久突然就开始下载了，而且很快就下载完了，这个看起来好像不太正常，一般加入之后不是很大文件很快就完成，好像是卡在哪个地方了，在某个时刻才会开始走下载

**Comment by 9527kevin** [comment]
我也遇到了，怎么解决？
