### ISSUE TITLE
multiDownload开启一批下载，实际上并不是在前台开启所有下载？切到后台后很快就不继续下了

### ISSUE THREAD

**Issue by fuxingwe** [Danie1s/Tiercel#147]

**Comment by Danie1s** [comment]
系统把下载的最大并发数限制到6，所以没必要马上把所有任务都开启。
至于切到后台，系统也会限制后台下载的使用，不会没有继续下，只是有一个延迟，而这个延迟会越来越大，所以如果有很多小文件的话，建议打包成大文件下载
