### ISSUE TITLE
[DownloadTask] running 下载文件没有成功或者失败回调

### ISSUE THREAD

**Issue by f513234428** [Danie1s/Tiercel#148]
https://test-azure-community.obs.cn-south-1.myhuaweicloud.com/20210528140741%2F75d69922aef24812912ad259f01e8ec9.jpeg
用的是最新的SDK
这个文件在demo里面没有收到下载成功回调,跟上一个running卡住问题一样,奇怪的是ViewController2中是能下载成功的,但是剩下3个会卡住,暂时排查不出问题,麻烦看下.

**Comment by Danie1s** [comment]
![image](https://user-images.githubusercontent.com/19432029/119997268-23eaf380-c002-11eb-9d59-3ddff66c3259.png)

**Comment by f513234428** [comment]
谢了,确实是线程问题,已经处理好了
