### ISSUE TITLE
大佬可以吧原始downloadtask id暴露出来吗 

### ISSUE THREAD

**Issue by roycehe** [Danie1s/Tiercel#149]
或者task是否有唯一标识 用url不可靠

**Comment by Danie1s** [comment]
![image](https://user-images.githubusercontent.com/19432029/121848213-4d9f5c80-cd1c-11eb-9592-1eea06a338ae.png)
原始downloadtask id 只是一个简单的 Int

请问什么情况下 url 不可靠？
