### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by 350541732** [Danie1s/Tiercel#15]
真机提示这个错误
Undefined symbols for architecture arm64:
  "protocol witness table for Swift.Int64 : Tiercel.TiercelCompatible in Tiercel", referenced from:
麻烦大佬看一下

**Comment by Danie1s** [comment]
不好意思，我的库是肯定没问题的，这么多人用了都没提过这个问题，而且我自己公司的项目也在用，你这个问题麻烦你自己去百度吧

> https://www.cnblogs.com/zhanglinfeng/p/5774033.html

**Comment by 350541732** [comment]
ok 3q

**Comment by 350541732** [comment]
@Danie1s  打包您的demo也显示错误 如下：
Undefined symbols for architecture arm64:
  "protocol witness table for __ObjC.UIDevice : Tiercel.TiercelCompatible in Tiercel", referenced from:
      Demo.BaseViewController.viewDidLoad() -> () in BaseViewController.o
  "protocol witness table for Swift.Int64 : Tiercel.TiercelCompatible in Tiercel", referenced from:
