### ISSUE TITLE
oss带验证参数和过期时间限制的url断点续传问题

### ISSUE THREAD

**Issue by CoderGFWu** [Danie1s/Tiercel#150]
阿里云oss的文件url带有验证参数和有效期限制， 每次过期后只有参数部分会发生变化，请问可以把资源的唯一性做成URL的absolute， 从而实现断点续传的功能

**Comment by Danie1s** [comment]
你是说 url.absoluteString ？这个也是包括参数的

**Comment by CoderGFWu** [comment]
那可能是我表述错了， 我的意思就是不要用完整的url作为资源的唯一标识， 比如https://xxx.xxx.xxx/xxx/xxx?x=xxx&x=xxx 只取？前面的部分‘ https://xxx.xxx.xxx/xxx/xxx ’作为资源的唯一标识， 又或者提供一个接口， 让开发者自定义每个下载资源的唯一标识

**Comment by Danie1s** [comment]
> 开发者自定义每个下载资源的唯一标识

这个可以，我找个时间更新
