### ISSUE TITLE
开启任务，但没反应，没回调.

### ISSUE THREAD

**Issue by zzzzzyijie** [Danie1s/Tiercel#151]
我这边有一个情况：

传入url  （url有效）, 但没反应，也没有成功或失败的回调。

这是什么原因呢？ 

log如下:

************************ TiercelLog ************************
identifier    :  xxxxx.xxxResources
Message       :  [SessionManager] running, tasks.count: 19

**Comment by zzzzzyijie** [comment]
> 我这边有一个情况：
> 
> 传入url （url有效）, 但没反应，也没有成功或失败的回调。
> 
> 这是什么原因呢？
> 
> log如下:
> 
> ************************ TiercelLog ************************
> identifier : xxxxx.xxxResources
> Message : [SessionManager] running, tasks.count: 19

iOS  14.6 
iPhone 8 Plus

**Comment by zzzzzyijie** [comment]
用的版本是 3.2.1
比较奇怪的是： 在我的设备是没问题（应该说大部分设备没问题）
有部分用户会有出现这个情况，是什么原因呢 ？

**Comment by zzzzzyijie** [comment]
> 我这边有一个情况：
> 
> 传入url （url有效）, 但没反应，也没有成功或失败的回调。
> 
> 这是什么原因呢？
> 
> log如下:
> 
> ************************ TiercelLog ************************
> identifier : xxxxx.xxxResources
> Message : [SessionManager] running, tasks.count: 19

我这边Log排查了一下； 这个url 的任务在缓存里有（fetchTask，但拿到的task状态为 willSuspend，所以没走下载逻辑；这是bug吗？  （ 我认为这里的download() 逻辑上有一些status被default break，也没有回调，这是为什么呢 ？
![image](https://user-images.githubusercontent.com/17098514/123198594-f5b4e280-d4df-11eb-8982-d5f3b49af93d.png)

**Comment by Danie1s** [comment]
卸载 App，重试

**Comment by zzzzzyijie** [comment]
> 卸载 App，重试

卸载应该是可以的，但是在逻辑怎么处理避免呢？ （ 而且让用户卸载来解决，不太好..）

**Comment by zzzzzyijie** [comment]
> 卸载 App，重试

我这边重现了一个测试了下：
确定是
 didStart()  时 的 status = running
  download() 时 的 status = willSuspend
 
 所以导致没有回调,  我这边的暂时处理是方案，如果拿到的task == .  willSuspend,  先移除掉再去重现下载..
 
 希望可以找出问题和优化~

**Comment by Danie1s** [comment]
[iOS-原生级别后台下载详解](https://github.com/Danie1s/Tiercel/wiki/iOS-%E5%8E%9F%E7%94%9F%E7%BA%A7%E5%88%AB%E5%90%8E%E5%8F%B0%E4%B8%8B%E8%BD%BD%E8%AF%A6%E8%A7%A3)

![image](https://user-images.githubusercontent.com/19432029/123276410-b9ad6c00-d537-11eb-8fc4-9f7d5c10fc68.png)

你出现这种情况是因为图片上的那个原因，估计是你断点调试时，又重新运行了项目

在用户真实的使用场景中，是不会发生这种情况的

**Comment by zzzzzyijie** [comment]
> [iOS-原生级别后台下载详解](https://github.com/Danie1s/Tiercel/wiki/iOS-%E5%8E%9F%E7%94%9F%E7%BA%A7%E5%88%AB%E5%90%8E%E5%8F%B0%E4%B8%8B%E8%BD%BD%E8%AF%A6%E8%A7%A3)
> 
> ![image](https://user-images.githubusercontent.com/19432029/123276410-b9ad6c00-d537-11eb-8fc4-9f7d5c10fc68.png)
> 
> 你出现这种情况是因为图片上的那个原因，估计是你断点调试时，又重新运行了项目
> 
> 在用户真实的使用场景中，是不会发生这种情况的

但确实是真实的用户反馈😂（当时解决方案是卸载重装就好了），我也找有出现情况的机子看过（也连他的手机调试过），确实会没有回调的情况； 

我这边的逻辑： 一个单例，然后持有一个SessionManager，再在SessionManager里download 不同url操作;  

好吧，这情况确实不好重现和解决（我这边是有好几个用户反馈这个问题）。

**Comment by Danie1s** [comment]
首先，你卸载 App，重新安装后，不做任何断点调试，正常的使用下，会出现这个问题吗？

其次，你能在demo上复现吗？

**Comment by moo611** [comment]
确实是断点导致的
