### ISSUE TITLE
第一次download、multiDownload，[DownloadTask] suspended

### ISSUE THREAD

**Issue by caosuyang** [Danie1s/Tiercel#152]
************************ TiercelLog ************************
Message       :  [SessionManager] running, tasks.count: 1

总任务：0/1
************************ TiercelLog ************************
Message       :  [DownloadTask] suspended

总速度：0 KB/s
剩余时间： 0
总进度： 0.00

**Comment by caosuyang** [comment]
总任务：0/24
总速度：0 KB/s
************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [SessionManager] running, tasks.count: 24

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  https://jszoem-1253248774.cos.ap-shanghai.myqcloud.com/2018%E4%B8%AD%E5%AD%A6/%E6%95%99%E7%9F%A5/10%E8%B5%AB%E5%B0%94%E5%B7%B4%E7%89%B9%E7%9A%84%E6%95%99%E8%82%B2%E6%80%9D%E6%83%B3.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/%E8%80%83%E6%83%85%E5%88%86%E6%9E%901.mp4.f30.mp4

剩余时间： 0
************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/1%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%E6%A6%82%E8%BF%B0%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/2%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%E6%A6%82%E8%BF%B0%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%BA%8C%E8%8A%82.mp4.f30.mp4

总进度： 0.00
parameters: ["courseId": 26, "coursewareId": 38]
************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/3%E5%B9%BC%E5%84%BF%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%20%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4

url: http://134.175.238.248/bwx/api/studyRecord/getCoursewareStudyRecord/26/38
************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/4%E5%B9%BC%E5%84%BF%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%20%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%BA%8C%E8%8A%82.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/5%E5%B9%BC%E5%84%BF%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%E7%9A%84%E5%AE%9E%E6%96%BD%20%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/6%E5%84%BF%E7%AB%A5%E8%A7%82%E4%BA%BA%E7%9A%84%E5%85%A8%E9%9D%A2%E5%8F%91%E5%B1%95%E6%80%9D%E6%83%B3%E6%A6%82%E8%BF%B0%20%E7%AC%AC%E4%BA%8C%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/7%E2%80%9C%E8%82%B2%E4%BA%BA%E4%B8%BA%E6%9C%AC%E2%80%9D%20%E7%9A%84%E5%84%BF%E7%AB%A5%E8%A7%82%20%E7%AC%AC%E4%BA%8C%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/8%E2%80%9C%E8%82%B2%E4%BA%BA%E4%B8%BA%E6%9C%AC%E2%80%9D%20%E7%9A%84%E5%84%BF%E7%AB%A5%E8%A7%82%20%E7%AC%AC%E4%BA%8C%E7%AB%A0%20%E7%AC%AC%E4%BA%8C%E8%8A%82.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/9%20%E2%80%9C%E8%82%B2%E4%BA%BA%E4%B8%BA%E6%9C%AC%E2%80%9D%E7%9A%84%E6%95%99%E8%82%B2%E8%A7%82%E5%9C%A8%E4%BF%9D%E6%95%99%E5%AE%9E%E8%B7%B5%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/10%E6%9E%84%E5%BB%BA%E8%89%AF%E5%A5%BD%E7%9A%84%E5%B8%88%E5%B9%BC%E5%85%B3%E7%B3%BB.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/11%E6%95%99%E5%B8%88%E8%A7%82.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/12%E7%8E%B0%E4%BB%A3%E6%95%99%E5%B8%88%E8%A7%82%EF%BC%88%E4%B8%80%EF%BC%89.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/13%E7%8E%B0%E4%BB%A3%E6%95%99%E5%B8%88%E8%A7%82%EF%BC%88%E4%BA%8C%EF%BC%89.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/14%E5%B9%BC%E5%B8%88%E6%95%99%E8%82%B2%E7%9A%84%E4%B8%93%E4%B8%9A%E5%8F%91%E5%B1%95.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/15%E5%B9%BC%E5%84%BF%E6%95%99%E5%B8%88%E7%9A%84%E7%BB%88%E8%BA%AB%E5%AD%A6%E4%B9%A0.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/36%E6%95%99%E8%82%B2%E6%B3%95%E7%9A%84%E5%9F%BA%E6%9C%AC%E7%9F%A5%E8%AF%86%20%E6%95%99%E8%82%B2%E6%B3%95%E5%BE%8B%E8%B4%A3%E4%BB%BB.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B0%8F%E5%AD%A6/%E7%BB%BC%E5%90%88/129%E8%80%83%E6%83%85%E5%88%86%E6%9E%90.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E4%B8%AD%E5%AD%A6/%E7%BB%BC%E5%90%88/76%E6%95%99%E8%82%B2%E8%A7%82%20%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%E7%9A%84%E5%AE%9E%E6%96%BD%20%20%20%20%20%20.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E4%B8%AD%E5%AD%A6/%E7%BB%BC%E5%90%88/80%E5%AD%A6%E7%94%9F%E8%A7%82%20%E2%80%9C%E4%BB%A5%E4%BA%BA%E4%B8%BA%E6%9C%AC%E2%80%9D%E5%AD%A6%E7%94%9F%E8%A7%82%E7%9A%84%E6%A6%82%E8%BF%B0.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E4%B8%AD%E5%AD%A6/%E7%BB%BC%E5%90%88/78%E5%AD%A6%E7%94%9F%E8%A7%82%20%E2%80%9C%E4%BA%BA%E7%9A%84%E5%85%A8%E9%9D%A2%E5%8F%91%E5%B1%95%E2%80%9D%E7%9A%84%E6%A6%82%E8%BF%B0%20%20.mp4.f30.mp4

sectionUrl https://jszoem-1253248774.cos.ap-shanghai.myqcloud.com/2018%E4%B8%AD%E5%AD%A6/%E6%95%99%E7%9F%A5/10%E8%B5%AB%E5%B0%94%E5%B7%B4%E7%89%B9%E7%9A%84%E6%95%99%E8%82%B2%E6%80%9D%E6%83%B3.mp4.f30.mp4
0.0 0.0 0.0
************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E4%B8%AD%E5%AD%A6/%E7%BB%BC%E5%90%88/87%E6%95%99%E8%82%B2%E6%B3%95%E5%BE%8B%E6%B3%95%E8%A7%84%20%E6%95%99%E8%82%B2%E6%B3%95%E5%BE%8B%E5%85%B3%E7%B3%BB%20.mp4.f30.mp4

************************ TiercelLog ************************
identifier    :  com.banwokao.study.OfflineVideoViewController_26
Message       :  [DownloadTask] suspended
Task URL      :  http://jszoem-1253248774.cossh.myqcloud.com/2018%E4%B8%AD%E5%AD%A6/%E7%BB%BC%E5%90%88/89%E6%95%99%E8%82%B2%E6%B3%95%E5%BE%8B%E6%B3%95%E8%A7%84%20%E6%95%99%E8%82%B2%E6%B3%95%E5%BE%8B%E8%B4%A3%E4%BB%BB%20.mp4.f30.mp4

parameters: ["coursewareId": 41, "courseId": 26]
url: http://134.175.238.248/bwx/api/studyRecord/getCoursewareStudyRecord/26/41
parameters: ["courseId": 26, "coursewareId": 44]
url: http://134.175.238.248/bwx/api/studyRecord/getCoursewareStudyRecord/26/44
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/%E8%80%83%E6%83%85%E5%88%86%E6%9E%901.mp4.f30.mp4
0.0 0.0 0.0
parameters: ["coursewareId": 44, "courseId": 26]
url: http://134.175.238.248/bwx/api/studyRecord/getCoursewareStudyRecord/26/44
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/1%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%E6%A6%82%E8%BF%B0%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/2%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%E6%A6%82%E8%BF%B0%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%BA%8C%E8%8A%82.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/3%E5%B9%BC%E5%84%BF%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%20%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/4%E5%B9%BC%E5%84%BF%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%20%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%BA%8C%E8%8A%82.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/5%E5%B9%BC%E5%84%BF%E7%B4%A0%E8%B4%A8%E6%95%99%E8%82%B2%E7%9A%84%E5%AE%9E%E6%96%BD%20%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/6%E5%84%BF%E7%AB%A5%E8%A7%82%E4%BA%BA%E7%9A%84%E5%85%A8%E9%9D%A2%E5%8F%91%E5%B1%95%E6%80%9D%E6%83%B3%E6%A6%82%E8%BF%B0%20%E7%AC%AC%E4%BA%8C%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/7%E2%80%9C%E8%82%B2%E4%BA%BA%E4%B8%BA%E6%9C%AC%E2%80%9D%20%E7%9A%84%E5%84%BF%E7%AB%A5%E8%A7%82%20%E7%AC%AC%E4%BA%8C%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/8%E2%80%9C%E8%82%B2%E4%BA%BA%E4%B8%BA%E6%9C%AC%E2%80%9D%20%E7%9A%84%E5%84%BF%E7%AB%A5%E8%A7%82%20%E7%AC%AC%E4%BA%8C%E7%AB%A0%20%E7%AC%AC%E4%BA%8C%E8%8A%82.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/9%20%E2%80%9C%E8%82%B2%E4%BA%BA%E4%B8%BA%E6%9C%AC%E2%80%9D%E7%9A%84%E6%95%99%E8%82%B2%E8%A7%82%E5%9C%A8%E4%BF%9D%E6%95%99%E5%AE%9E%E8%B7%B5%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E7%AC%AC%E4%B8%80%E8%8A%82.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/10%E6%9E%84%E5%BB%BA%E8%89%AF%E5%A5%BD%E7%9A%84%E5%B8%88%E5%B9%BC%E5%85%B3%E7%B3%BB.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/11%E6%95%99%E5%B8%88%E8%A7%82.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/12%E7%8E%B0%E4%BB%A3%E6%95%99%E5%B8%88%E8%A7%82%EF%BC%88%E4%B8%80%EF%BC%89.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/13%E7%8E%B0%E4%BB%A3%E6%95%99%E5%B8%88%E8%A7%82%EF%BC%88%E4%BA%8C%EF%BC%89.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/14%E5%B9%BC%E5%B8%88%E6%95%99%E8%82%B2%E7%9A%84%E4%B8%93%E4%B8%9A%E5%8F%91%E5%B1%95.mp4.f30.mp4
0.0 0.0 0.0
sectionUrl http://jszoem-1253248774.cossh.myqcloud.com/2018%E5%B9%BC%E5%84%BF/%E7%BB%BC%E5%90%88/15%E5%B9%BC%E5%84%BF%E6%95%99%E5%B8%88%E7%9A%84%E7%BB%88%E8%BA%AB%E5%AD%A6%E4%B9%A0.mp4.f30.mp4
0.0 0.0 0.0
总任务：0/24
总速度：0 KB/s
剩余时间： 0
总进度： 0.00
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0
0.0 0.0 0.0

**Comment by Danie1s** [comment]
你有用 demo 试过吗？

**Comment by caosuyang** [comment]
demo，没有问题，已经找到原因，是我在外部初始化相同标识的SessionManager导致
