### ISSUE TITLE
和Kingfisher 不兼容？

### ISSUE THREAD

**Issue by dd9913762113** [Danie1s/Tiercel#155]
Kingfisher有 DownloadTask
Tiercel 有  DownloadTask

import Kingfisher
import Tiercel
放在一个类里面
就报错了
'DownloadTask' is ambiguous for type lookup in this context

建议给库和方法加前缀

**Comment by Danie1s** [comment]
命名空间问题。可以用 Kingfisher. DownloadTask 和T iercel.DownloadTask 区分
