### ISSUE TITLE
删除全部正在下载的任务后，等待下载的任务不能自动开始

### ISSUE THREAD

**Issue by JoanLeeo** [Danie1s/Tiercel#159]

**Comment by demoker** [comment]
在后台下载过程中，对于在后台新创建的NSURLSessionDownloadTask，无法开始下载，大佬有什么好的想法吗？

**Comment by Danie1s** [comment]
@JoanLeeo 你有demo试过吗？

**Comment by Danie1s** [comment]
@demoker 搜一下其他 issue，或者看一下 wiki

**Comment by JoanLeeo** [comment]
删除全部正在下载的任务后，等待下载的任务不能自动开始
https://user-images.githubusercontent.com/9317498/132611479-93c132af-6dd0-4859-af98-22bd60870323.mp4
