### ISSUE TITLE
示例demo打包报错

### ISSUE THREAD

**Issue by 350541732** [Danie1s/Tiercel#16]
您好 下载您的demo示例打包之后显示的错误为:
Undefined symbols for architecture armv7:
  "protocol witness table for __ObjC.UIDevice : Tiercel.TiercelCompatible in Tiercel", referenced from:
      Demo.BaseViewController.viewDidLoad() -> () in BaseViewController.o
  "protocol witness table for Swift.Int64 : Tiercel.TiercelCompatible in Tiercel", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of Demo.ViewController1.(updateUI in _5C5E94575650EAFC2B93D94793CAD274)(Tiercel.TRTask) -> () in ViewController1.o
麻烦可以看一下吗？谢谢

**Comment by Danie1s** [comment]
我没有把示例demo打包，因为打包配置证书之类的，比较麻烦，但刚刚我把使用这个库的项目打包了，发现并没有出现问题。
我觉得是你的项目设置，或者xcode的设置有问题吧。
