### ISSUE TITLE
遇到个问题

### ISSUE THREAD

**Issue by gaoruiqing187** [Danie1s/Tiercel#161]
最近开发中遇到个问题，有两个走进度的cell，第一个下载完成刷新tableview，第二个的进度条直接就满了，但是并未下载完成

**Comment by Danie1s** [comment]
这个是cell复用的问题，你可以参考demo

**Comment by gaoruiqing187** [comment]
我是参考了demo，demo中下载完成不会移除这个cell，我这移除之后刷新了tableview






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Danie1s/Tiercel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Danie1s/Tiercel] 遇到个问题 (#161)





 
这个是cell复用的问题，你可以参考demo
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Danie1s** [comment]
刷新不影响的，你想办法把之前的进度回调都移除吧
