### ISSUE TITLE
删除全部正在下载的任务后，等待下载的任务不能自动开始

### ISSUE THREAD

**Issue by JoanLeeo** [Danie1s/Tiercel#163]
https://user-images.githubusercontent.com/9317498/132611479-93c132af-6dd0-4859-af98-22bd60870323.mp4 # # #159

**Comment by Danie1s** [comment]
你先用 demo 进行测试

**Comment by JoanLeeo** [comment]
@Danie1s 我已经在你的demo里试过了，发现还是这个问题，这次我特意等待了很长时间，在把正在下载的任务删除之后，等待的任务是没有开始下载的。到最后，我开始下载之后才下载完成的。这次我录了一个长的视频你看一下我的操作是否有问题。

https://user-images.githubusercontent.com/9317498/133867123-e32845c8-6ece-4f38-987e-77e5c4b0b50f.mp4

**Comment by Danie1s** [comment]
你好，我测试以后，确实发现有问题，很抱歉。我会尽快更新
