### ISSUE TITLE
批量下载，下载完成自动移除

### ISSUE THREAD

**Issue by luwenhan2018** [Danie1s/Tiercel#165]
批量下载时，每下载完一条从tasks中移除刷新表后，后面cell 中的数据会显示0，但是进度条在走下载到本地的文件也是正常的就会说表中的数据会出现错乱，希望作者能扩展自动移除功能
![Uploading 图片.png…]()

**Comment by Danie1s** [comment]
不好意思，没看懂你说的是什么情况，图片也显示不出来，麻烦你重新再说一遍问题
