### ISSUE TITLE
重启App后沙盒路径变化导致报错

### ISSUE THREAD

**Issue by cookle** [Danie1s/Tiercel#171]
1.Xcode真机调试，启动下载，返回主页
2.此时后台下载中，Xcode点击停止按钮模拟被系统Kill
3.等待后台下载完成，Xcode点击运行启动App
4.报store file failed，看了下nsurlsessiond进程下载的文件路径与缓存路径不符，原因是每次App冷启动沙盒路径都会改变，因此再用上一次缓存的路径就报错了

**Comment by cookle** [comment]
忘了说了，版本是3.2.5

**Comment by Danie1s** [comment]
这是正常的表现。只有用Xcode重新运行的时候才会出现，在真实的环境中是没问题的。
我这篇[文章](https://github.com/Danie1s/Tiercel/wiki/iOS-%E5%8E%9F%E7%94%9F%E7%BA%A7%E5%88%AB%E5%90%8E%E5%8F%B0%E4%B8%8B%E8%BD%BD%E8%AF%A6%E8%A7%A3)中也有说明

**Comment by moo611** [comment]
> 1.Xcode真机调试，启动下载，返回主页 2.此时后台下载中，Xcode点击停止按钮模拟被系统Kill 3.等待后台下载完成，Xcode点击运行启动App 4.报store file failed，看了下nsurlsessiond进程下载的文件路径与缓存路径不符，原因是每次App冷启动沙盒路径都会改变，因此再用上一次缓存的路径就报错了

只缓存文件名试试
