### ISSUE TITLE
stuck on .willSuspend Status

### ISSUE THREAD

**Issue by mahadshahib** [Danie1s/Tiercel#173]
hello,
I am using URLSession default configuration for my uses when the user terminates app download task will be stuck on .willSuspend or .running state and there is no way to resume download again what is the solution?

**Comment by Danie1s** [comment]
Please update to the latest version and try again.

**Comment by 2228505521** [comment]
请问这个问题解决了吗？我使用的是3.2.2版本，同样出现了这个问题：手动kill掉应用，再次打开无论如何都不能重新开始下载呢，虽然task的状态都是running

**Comment by Danie1s** [comment]
@2228505521 下载最新的版本就可以解决了吧

**Comment by mahadshahib** [comment]
> 请问这个问题解决了吗？我使用的是3.2.2版本，同样出现了这个问题：手动kill掉应用，再次打开无论如何都不能重新开始下载呢，虽然task的状态都是running

Inside DownloadTask class there is a switch statement which says when state is x do y , when you manually kill the app the state of task will be .willSuspend so you need to add this state to that particular switch statement in order to start download even when task is .willSuspend
