### ISSUE TITLE
多任务tasks下载时，会多次触发failure回调

### ISSUE THREAD

**Issue by iband2011** [Danie1s/Tiercel#178]
let tasks = sessionManager.multiDownload(urls)
tasks.success(onMainQueue: true) { task in

}.failure(onMainQueue: true) { task in
    if task.status == .removed {
        return
    }
    failure?()
}

//---------------
当调用sessionManager.totalRemove()方法时，上面的failure block会被多次触发

**Comment by Danie1s** [comment]
这是正常的，因为你设置的回调的对象是 tasks
