### ISSUE TITLE
如果请求的地址返回404依旧提示下载成功，应该做statusCode的异常处理

### ISSUE THREAD

**Issue by const-zhou** [Danie1s/Tiercel#18]
应该对response的statuscode进行处理，目前添加了一个404的处理如下：
TRDownloadTask.swift文件下196行加入：
        if response.statusCode == 404 {
            completed()
            manager?.completed()
            completionHandler(.cancel)
            return
        }

望完善对应的statuscode处理

**Comment by Danie1s** [comment]
非常感谢您提出的问题，让你的使用造成不便，非常抱歉，这一点可能确实没有考虑到，我会尽快修复，望见谅

**Comment by Danie1s** [comment]
已经更新
