### ISSUE TITLE
删除任务的问题

### ISSUE THREAD

**Issue by flyling** [Danie1s/Tiercel#183]
我想通过 self.sessionManager.cache.fileExists(url: url) 判断是不是文件存在  如果存在 我就不再重复下载,如果不存在我就删除之前的task   重新下载 我发现我下载下来的文件名和你代码里的文件名 类似543e0195bfcd5a416b8f6f2aa5b24d96.mp4文件名是不一样的 所以永远是false     有没有更好的方法呢 希望大佬解惑    期待早点回复 😭着急

**Comment by Danie1s** [comment]
我测试过是没有问题的，除非你手动改了文件名，请检测你的代码

**Comment by flyling** [comment]
你好，你的这个三方库非常赞，我遇到的问题是：默认的下载文件名是url的md5加上文件扩展名，但是下载的时候传进去了一个新名字self.sessionManager.download(downloadDataInfo.url,headers: headers,fileName: dstFileName)，请问这时候用这个 self.sessionManager.cache.fileExists(url: url)判断是不是已经下载过了就不对了。因为我里面跟踪代码发现里面判断用的文件名还是md5加上扩展名，没有用我传进去的文件名判断，准确的说没有用最终下载后task.filename判断。是这样吗？
