### ISSUE TITLE
Debouncer类的workItems字典有可能会引起资源竞争导致Crash

### ISSUE THREAD

**Issue by OldChicken** [Danie1s/Tiercel#184]
![1660722709320](https://user-images.githubusercontent.com/14247021/185064717-a7696335-3a21-4bba-b055-d36e151c5d5c.jpg)
第128行的self?.workItems.removeValue(forKey: label)和130行的workItems[label] = workItem可能同时发生在两个线程，导致Crash。

**Comment by Danie1s** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/19432029/185727644-bbd8744d-f110-4246-9313-a4a5b753b59d.png">
这里是有加锁的

**Comment by OldChicken** [comment]
> <img alt="image" width="570" src="https://user-images.githubusercontent.com/19432029/185727644-bbd8744d-f110-4246-9313-a4a5b753b59d.png">
> 
> 这里是有加锁的

是加锁了，但是你仔细看下，这个锁的作用域不包含self?.workItems.removeValue(forKey: label)这行代码，因为这行代码是在queue这个串行队列线程里执行的，而workItems[label] = workItem的执行线程是不确定的，你可以写个单元测试，外部使用多个线程执行debouncer.execute方法，还是比较容易复现Crash的。


经过我的测试，改成这样才是安全的。

![截屏2022-08-23 上午10 27 53](https://user-images.githubusercontent.com/14247021/186055569-61db77ae-7925-42ef-8653-51290b34959d.png)

**Comment by OldChicken** [comment]
> <img alt="image" width="570" src="https://user-images.githubusercontent.com/19432029/185727644-bbd8744d-f110-4246-9313-a4a5b753b59d.png">
> 
> 这里是有加锁的

是我下的版本太旧了，感谢。
