### ISSUE TITLE
URL 有空格 无法下载，不走成功也不走失败

### ISSUE THREAD

**Issue by smallgirl** [Danie1s/Tiercel#187]
下载地址如下 https://dow4.dowlzi.com/20220807/8264_b7073296/苍兰诀 (1).mp4
浏览器可以下载

Message       :  [DownloadTask] running
Task URL      :  https://dow4.dowlzi.com/20220807/8264_b7073296/%E8%8B%8D%E5%85%B0%E8%AF%80%20(1).mp4

**Comment by smallgirl** [comment]
```
  sessionManager.download(URLString.toURL()!) { [weak self] _ in
            guard let self = self else { return }
            let index = self.sessionManager.tasks.count - 1
            self.tableView.insertRows(at: [IndexPath(row: index, section: 0)], with: .automatic)
            self.updateUI()
        }


extension String {

    // 字符串转URL 处理中文问题
    func toURL() -> URL? {
        guard let newUrl = addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) else {
            return nil
        }
        guard let url = URL(string: newUrl) else {
            return nil
        }
        return url
    }
}


```
url 已经做了url encode 也不行

**Comment by Danie1s** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/19432029/190201864-3f1ddd2a-6da4-4ee8-a480-00253dda2103.png">

我用 Demo 测试是没问题的

**Comment by smallgirl** [comment]
找到问题了，这个域名ip是国外的，手机联网网络和vpn 都可以访问下载，移动宽带无法访问（移动主动屏蔽了国外ip），但是如果用移动宽带demo确实也是不走成功和失败一直卡住，用URLSession DownloadTask 也是一样卡住、不走任何回调。
