### ISSUE TITLE
多任务下载总进度问题

### ISSUE THREAD

**Issue by StarSkyK** [Danie1s/Tiercel#190]
运行了Demo的多任务，存在进度条一直来回变得情况，翻看了大佬的issues，看了大佬的部分回答，似乎说是由于任务一直在添加导致进度一直变，提到用
![image](https://user-images.githubusercontent.com/23426094/211343856-da828108-836e-4c21-a617-8c44eafcebdf.png)
这种形式来获取进度，但是似乎也会存在来回闪的问题
![image](https://user-images.githubusercontent.com/23426094/211343956-ffa5a8f4-0b99-4b6a-95c8-ccd640ab6839.png)
有什么好的方式可以解决这个问题呢

盼回复，谢谢大佬

**Comment by Danie1s** [comment]
目前没有办法解决这个问题

**Comment by StarSkyK** [comment]
已经有解决方式，服务器告知我所有文件大小总和即可
