### ISSUE TITLE
在初始化SessionManager的时候,触发了completion回调

### ISSUE THREAD

**Issue by moo611** [Danie1s/Tiercel#193]
我打算在回调里写一些业务逻辑，比如输出“下载完成”之类的。正常应该是下载完成才输出。但是如果我之前已经下载完成，重启app的时候，会自动触发completion回调，导致输出了“下载完成”。

**Comment by moo611** [comment]
有没有一种方法，能在初始化sessionmanager的时候，不触发回调呢？只在调用download或者multipleDownload的时候触发。

**Comment by Danie1s** [comment]
目前是这样，没办法
