### ISSUE TITLE
总的进度问题

### ISSUE THREAD

**Issue by YanshuangyingDarker** [Danie1s/Tiercel#196]
大佬辛苦看下呢，批量下载的时候（多个下载任务）  sessionManager.progress.fractionCompleted  在设置总进度的时候，不正确，很多时候还是返回的每个任务的进度，可以打印出来看下，并不是总的进度。辛苦大佬修改下呢，改如何修改呢？谢谢

**Comment by YanshuangyingDarker** [comment]
希望老板看到能够及时解决下呢

**Comment by Danie1s** [comment]
https://github.com/Danie1s/Tiercel/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%89%B9%E9%87%8F%E4%B8%8B%E8%BD%BD%E6%97%B6%E6%80%BB%E8%BF%9B%E5%BA%A6%E9%94%99%E4%B9%B1
