### ISSUE TITLE
后台下载问题

### ISSUE THREAD

**Issue by lixiang1994** [Danie1s/Tiercel#199]
下载队列一共4个任务, 最大并发为2, 开始下载 进入后台, 在后台会下载完成2个任务, 然后应用挂起, 剩下的2个任务不会再继续下载.

**Comment by lixiang1994** [comment]
@Danie1s

**Comment by Danie1s** [comment]
会的

**Comment by lixiang1994** [comment]
可是我用demo测试的表现是不会下载剩下的2个, 环境是 iOS17的iPhone15 Pro, Xcode 15.2
