### ISSUE TITLE
能否考虑将manager中task的存储方式改为字典？

### ISSUE THREAD

**Issue by latorex12** [Danie1s/Tiercel#2]
首先非常感谢大佬开源这个下载器源码。
看到源码中多处都是使用遍历匹配的方式来获取task，感觉换成字典性能应该会好很多。（强迫症）
或者说这样写是出于怎样的考虑呢？

**Comment by Danie1s** [comment]
使用数组保存tasks，是为了保证下载任务的顺序，如果用字典的话，还是需要要再添加一个属性来排序。感谢你的建议，我会考虑一下做这个优化，或者你有什么更好的想法，欢迎你给我建议，十分感谢！

**Comment by Danie1s** [comment]
@latorex12 已经在develop分支更新。考虑到给外部使用还是数组比较方便，所以字典属性是内部使用，减少遍历，但为了保证顺序，还是有些地方需要遍历，暴露出来的tasks还是数组
