### ISSUE TITLE
下载不支持

### ISSUE THREAD

**Issue by ZClee128** [Danie1s/Tiercel#201]
http://www.iesdouyin.com/aweme/v1/play/?video_id=v0300fg10000cmijolbc77u0bmnp2u5g&ratio=1080p&line=0
这个连接下载没有反应，但是在浏览器是可以下载的

**Comment by Danie1s** [comment]
<img width="393" alt="image" src="https://github.com/Danie1s/Tiercel/assets/19432029/70089a5f-1e67-48a1-a84b-c05be685ef99">
你用demo去试试，没问题的
