### ISSUE TITLE
希望大神增加一个 waitsForConnectivity  让使用者来控制断网情况是要等待网络，还是直接失败。

### ISSUE THREAD

**Issue by qinge** [Danie1s/Tiercel#206]
希望大神能在 SessionConfiguration 暴露一个 waitsForConnectivity 属性，用来配置  URLSessionConfiguration 的同名属性，让使用者来控制断网情况是要等待网络，还是直接失败。

**Comment by Danie1s** [comment]
该属性的文档：
This property is ignored by background sessions, which always wait for connectivity.
