### ISSUE TITLE
下载完成后，将文件移动到其他位置，再次下载时提示下载成功，但是没有走真正的下载，而是fetch原来的task并获取状态

### ISSUE THREAD

**Issue by xindizhiyin2014** [Danie1s/Tiercel#209]
你好，请问是否可以暴露一个方法，允许用户手动清理掉已经完成task信息，把他从tasks的系列数组中移除掉，下次fetch的时候获取不到，重新下载。谢谢

**Comment by Danie1s** [comment]
本来就有这么一个方法。 
`SessionManager.remove(_:completely:onMainQueue:handler:)`  
completely 传 true

**Comment by xindizhiyin2014** [comment]
好的，谢谢
