### ISSUE TITLE
您好，现在我在用您的框架来下载m3u8，我这边添加了解析m3u8的类，但是到下载的时候显示出了下载多个ts文件的进度。请问一下如果是下载m3u8的文件，应该怎么处理呢？

### ISSUE THREAD

**Issue by xiaoAdev** [Danie1s/Tiercel#21]

**Comment by xiaoAdev** [comment]
第一个是如何只显示一个下载进度。第二个是如果实现多个下载m3u8。麻烦能指点一下吗？

**Comment by Danie1s** [comment]
m3u8是一种文本文件，非视频文件，是用utf-8描述的文本文件，是一个播放列表。你解析出来应该是多个视频文件的url，所以下载时是显示多个ts文件，这是没错的。Tiercel只是提供文件的下载，而这些媒体文件需要你自己额外处理。你应该要先下载这个ts文件，然后把他们合并，再转成你需要的媒体格式（如mp4）
