### ISSUE TITLE
库中的错误异常大部分都吞掉没有暴露出来, 这样真的好吗?

### ISSUE THREAD

**Issue by wolfcon** [Danie1s/Tiercel#22]
比如创建目录, 删除缓存等等, 其他的不列举了.

Swift 类默认给了 `throws` . 应该最好不要忽略掉那些错误, 有时候可能正是那些莫名的错误导致功能异常, 而没有暴露给外部去处理. 作为一个第三方库, 不太合理

**Comment by Danie1s** [comment]
谢谢你提出的建议，我看了一下，其实你说的那些错误我几乎都有用了`if let`，已经考虑了出错的情况，只不过没有用`do catch`来处理，没有把`error`打印出来，我会进行一些改进

**Comment by wolfcon** [comment]
因为 `catch` 后, 有一些也是没有向外部暴露这个错误, 其实应该整理一下, 在适当的位置 `throw` 出去 

有一些是用 `if let` 提前判断了. 其实 `try catch` 的过程就是让错误更加集中, 便于阅读. 不要考虑前后关系来的. 不知道我说明白了没有 🤪
