### ISSUE TITLE
App运行期间，已经下载的文件，再次调用下载不会走completion回调

### ISSUE THREAD

**Issue by SSBun** [Danie1s/Tiercel#25]
![image](https://user-images.githubusercontent.com/13583118/51973475-b4f44300-24b8-11e9-8666-d7cff958f936.png)
1.在app运行期间， 已经下载完成的文件，task还保留在manager当中，再次下载时判断已经在本地了，会直接调用`  task.completed()`但是此时的status已经是completed所已就没有回调了

**Comment by Danie1s** [comment]
我这样写的目的是，当task还在manager中的时候，只会回调一次。
请问你需要的效果是？

**Comment by SSBun** [comment]
比如在app运行当中，我需要重复使用一些下载的素材，因为你自带缓存机制，我可以统一在每个模块都直接调用download，如果已经下载了就会直接返回成功了，这样就比较舒服了，不过，现在我可以通过成功后就直接移除task来解决这个问题

其实这里的completed不做这个判断好像也不会出现多次调用的风险，倒不如放宽限制解决这个问题，或者这里特殊说明一下吧，要不然真的容易当bug
![image](https://user-images.githubusercontent.com/13583118/52026219-098fd080-2542-11e9-9ec4-18500b9381e4.png)

**Comment by Danie1s** [comment]
从设计的角度来说，这个成功的回调，是指任务创建后下载这一个过程的成功，所以只存在成功一次。关于易用性，我会再考虑如何设计会更加方便，感谢你的建议。
你可以下载前先检查一边，是否本地已经存在
```swift
if TRManager.default.cache.fileExists(URLString: "下载的url") {
    // 需要执行的操作
} else {
    TRManager.default.download("下载的url")?.success({ (task) in
        // 需要执行的操作
    })
}
```
