### ISSUE TITLE
关于suspend和cancelByProducingResumeData的优缺点

### ISSUE THREAD

**Issue by helele90** [Danie1s/Tiercel#35]
我之前一般是使用suspend暂停，然后resume恢复。
如果出错调用了 didCompleteWithError，我再获取resumeData重新创建下载。
suspend 相比 cancelByProducingResumeData 有其他的什么坑吗，之前没遇到过。
suspend一般手动kill app 就会调用 didCompleteWithError。

**Comment by Danie1s** [comment]
我本来也打算用suspend来暂停task，但是在iOS 10.0，模拟器上出现crash后如果不马上resume，则无法恢复下载，所以只能用回cancelByProducingResumeData

**Comment by helele90** [comment]
好的，谢谢
