### ISSUE TITLE
考虑移除文件名前缀 `TR` 

### ISSUE THREAD

**Issue by RecherJ** [Danie1s/Tiercel#36]
这种命名方式是 OC 语言风格的产物，Swift 中都是按模块划分的，移除更 swifty 。
使用时，已经有 `tr` 了，所以更不需要这样的命名风格。
建议考虑一下。

**Comment by Danie1s** [comment]
谢谢你给的建议，我之前也考虑过，去掉前缀以后有些类比较容易起冲突，而且原先使用的开发者也需要比较多的改动，所以暂时不变，或许更新到Swift 5.0的时候再移除吧
