### ISSUE TITLE
不适用php提供下载的场景

### ISSUE THREAD

**Issue by JQHee** [Danie1s/Tiercel#39]
api：http://120.76.240.104:8017/api/course/get_ppt_content?courseId=78&token=23812ba3-8df9-417c-a2af-9915b0773088
/api/course/get_ppt_content: 是通过php header头下载文件
courseId：表示是不同的文件

使用后文件不能区分：都是保存一个名get_ppt_content的文件

**Comment by Danie1s** [comment]
Tiercel提供了自定义文件名，这种情况下，你可以自己设置文件名
