### ISSUE TITLE
有循环引用，造成内存泄露

### ISSUE THREAD

**Issue by const-zhou** [Danie1s/Tiercel#41]
public class TRSessionDelegate: NSObject {
    public weak var manager: TRManager?
}

此处是否应该用weak来修饰manager? 不然会造成循环引用，请追查一下。

**Comment by Danie1s** [comment]
`delegate`被`session`引用，正常来说`manager`销毁之前，会销毁`session`，所以不会循环引用

事实上，`manager `是全局变量，不会销毁的，自然也不存在循环引用
