### ISSUE TITLE
沙盒文件被被删除

### ISSUE THREAD

**Issue by sunnyhigher** [Danie1s/Tiercel#42]

**Comment by sunnyhigher** [comment]
您好，非常感谢您开源的下载框架，框架非常好用，现在项目中存在一个问题，文件下载成功后，过一段时间就消失了，好像是被系统自动删除了。经反馈，有些是过一晚上就被删除了，有些是过几天被删除，请问您知道该如何解决这个问题吗？

**Comment by sunnyhigher** [comment]
非常感谢

**Comment by sunnyhigher** [comment]
非常感谢

**Comment by Danie1s** [comment]
文件下载成功后，默认保存在`caches`文件夹下对应的下载模块文件夹里，一般情况下是不会被自动清除，但是也不会备份到iTunes和iCloud里。
当手机可用存储容量不够的时候，系统会有可能自动清理`caches`文件夹下的数据。
所以如果你是要保证某些数据一定要存在的，请自行把数据移动到其他地方。如果是不需要暴露出来的，推荐`Library/Application Support `

**Comment by sunnyhigher** [comment]
好的，我试一试，非常感谢
