### ISSUE TITLE
重复回调

### ISSUE THREAD

**Issue by wwx1991** [Danie1s/Tiercel#44]
下载结果会回调两次

**Comment by Danie1s** [comment]
你好，我用demo测试了一下，并没有发现重复回调，你可以说具体点吗？

**Comment by wwx1991** [comment]
我在使用如下代码的时候发现success方法的闭包会回调两次, 代码如下:
`TRManager.default.success{ (_) in
                       
                    }
TRManager.default.multiDownload(urls)`
TRManager.default.success执行即得到回调(下载尚未开始), 待下载完成后success又得到一次回调

**Comment by Danie1s** [comment]
Tiercel会持久化任务，当你设置了回调，如果所有任务本来就下载完了，就会执行`manager`的成功回调

如果你开启新的下载，那总任务数量已经发生变化，当所有下载完成后，会再次执行成功回调
