### ISSUE TITLE
when downloading  crach ，this is the log

### ISSUE THREAD

**Issue by zymjjobs** [Danie1s/Tiercel#46]
iPhone system - iOS10.3

moveItem error: Error Domain=NSCocoaErrorDomain Code=516 "“CFNetworkDownload_J1VtL6.tmp” couldn’t be moved to “OM

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x131d38b10 of class __NSCFBackgroundDownloadTask was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x1744344c0> (
<NSKeyValueObservance 0x174056b60: Observer: 0x131d07ab0, Key path: currentRequest, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x174653f50>

**Comment by Danie1s** [comment]
请问是什么情况下出现的？

**Comment by Danie1s** [comment]
请试试新版
