### ISSUE TITLE
session.invalidateAndCancel() 问题

### ISSUE THREAD

**Issue by langzuxiaozi** [Danie1s/Tiercel#47]
` public var configuration = TRConfiguration() {
        didSet {
            guard !shouldCreatSession else { return }
            shouldCreatSession = true
            if status == .running {
                runningTasks = tasks.filter { $0.status == .running }
                waitingTasks = tasks.filter { $0.status == .waiting }
                totalSuspend()
            } else {
                session.invalidateAndCancel()
            }
        }
    }
`

对 configuration 赋值后，就没有机会创建新的 session，也就不能创建任务了吧

**Comment by Danie1s** [comment]
调用`session.invalidateAndCancel()`后，会在session的代理方法`didBecomeInvalidWithError`中创建新的session

**Comment by langzuxiaozi** [comment]
上周出现过几次崩溃，创建任务的时候使用了 session.invalidateAndCancel() 后的 session

**Comment by langzuxiaozi** [comment]
还偶尔出现  崩溃
 Trapped uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <Tiercel.TRDownloadTask 0x109e03190> for the key path "currentRequest" from <__NSCFBackgroundDownloadTask 0x109e0e870> because it is not registered as an observer.


	0   CoreFoundation                      0x000000018c861ed0 <redacted> + 256
	1   libobjc.A.dylib                     0x000000018ba5bf18 objc_exception_throw + 60
	2   CoreFoundation                      0x000000018c76408c <redacted> + 0
	3   Foundation                          0x000000018d23ca94 <redacted> + 496
	4   Foundation                          0x000000018d23c844 <redacted> + 96
	5   Tiercel                             0x00000001081ab4b0 $S7Tiercel14TRDownloadTaskC15startToDownload33_A7C9FB00241EA47A74A42D56B3A578C4LLyyF + 252
	6   Tiercel                             0x00000001081a75e0 $S7Tiercel14TRDownloadTaskC14prepareToStart33_A7C9FB00241EA47A74A42D56B3A578C4LLyyF + 300
	7   Tiercel                             0x00000001081a7438 $S7Tiercel14TRDownloadTaskC5startyyF + 2608
	8   Tiercel                             0x00000001081c0dd4 $S7Tiercel9TRManagerC13startNextTask33_3ACCD4FEA234297808199F0B298B355BLLyyFyAA6TRTaskCXEfU0_ + 60
	9   Tiercel                             0x000000010819bad8 $S7Tiercel6TRTaskCs5Error_pIggzo_ACsAD_pIegnzo_TR + 36
	10  Tiercel                             0x00000001081c3f2c $S7Tiercel6TRTaskCs5Error_pIggzo_ACsAD_pIegnzo_TRTA.122 + 40
	11  libswiftCore.dylib                  0x0000000108de5b0c $SSTsE7forEachyyy7ElementQzKXEKF + 448
	12  Tiercel                             0x00000001081c0054 $S7Tiercel9TRManagerC13startNextTask33_3ACCD4FEA234297808199F0B298B355BLLyyF + 856
	13  Tiercel                             0x00000001081be5d8 $S7Tiercel9TRManagerC9completedyyF + 144
	14  Tiercel                             0x00000001081afeec $S7Tiercel14TRDownloadTaskC11didComplete4task5errorySo012NSURLSessionC0C_s5Error_pSgtF + 8460
	15  Tiercel                             0x00000001081cc454 $S7Tiercel17TRSessionDelegateC10urlSession_4task20didCompleteWithErrorySo12NSURLSessionC_So0K4TaskCs0J0_pSgtF + 652
	16  Tiercel                             0x00000001081cc54c $S7Tiercel17TRSessionDelegateC10urlSession_4task20didCompleteWithErrorySo12NSURLSessionC_So0K4TaskCs0J0_pSgtFTo + 168

**Comment by Danie1s** [comment]
加我qq联系：176516837
