### ISSUE TITLE
success block里怎么获取文件本地地址?

### ISSUE THREAD

**Issue by hydyy** [Danie1s/Tiercel#48]
如题 , 回调回来是 TRTask , 不能直接回来download task吗? 而且, success 不应该是下载成功的回调吗? 我看demo中, 还在success 里判断status? 其他任何状态都应该是 faild回调呀

**Comment by Danie1s** [comment]
确实success里不需要判断了


获取文件地址请参考下面代码
```swift
success({ [weak self] (task) in
            if let task = task as? TRDownloadTask {
                let path = task.filePath
            }
        })
```
因为考虑到以后可能会添加上传功能，所以暂时没有直接返回TRDownloadTask
