### ISSUE TITLE
 is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by zmh10241015** [Danie1s/Tiercel#49]

**Comment by Danie1s** [comment]
？？？

**Comment by zmh10241015** [comment]
意思是Xcode有时候无法识别SessionManager这个类属于哪个包的需要 Tiercel. SessionManager来写。我觉得和前几个版本一样，类名前加一个前缀好一点。

**Comment by Danie1s** [comment]
swift的风格就这样，Tiercel. SessionManager用的地方不多吧
