### ISSUE TITLE
希望写一个OC版本的 谢谢

### ISSUE THREAD

**Issue by myiosemail** [Danie1s/Tiercel#53]

**Comment by Danie1s** [comment]
目前没有打算

**Comment by MQL9011** [comment]
OC 项目用这个库 用起来如何? 有人尝试过吗?

**Comment by Danie1s** [comment]
@myiosemail @MQL9011 
现在可以使用 [TiercelObjCBridge](https://github.com/Danie1s/TiercelObjCBridge) 进行桥接了
