### ISSUE TITLE
请问, 我遇到批量下载, 加载下载任务时卡住了. 

### ISSUE THREAD

**Issue by MQL9011** [Danie1s/Tiercel#54]
批量下载音频文件,  大概批量下300条左右数据时, 就会卡主线程.  
有好的优化建议吗
![image](https://user-images.githubusercontent.com/11871158/59240833-f7344a80-8c37-11e9-87e8-b6df11e8e98d.png)

**Comment by Danie1s** [comment]
在子线程异步开启任务
