### ISSUE TITLE
fileExists 判断异常

### ISSUE THREAD

**Issue by licheng0508** [Danie1s/Tiercel#55]
Cache.swift

    public func fileExists(fileName: String) -> Bool {
        guard let path = filePath(fileName: fileName) else { return false }
        return fileManager.fileExists(atPath: path)
    }

这里判断文件用 fileExists  返回是true但文件打不开(下载的图片在File中显示为0B 且打不开但是显示下载成功)
建议用 isExecutableFile 判断

**Comment by Danie1s** [comment]
`fileExists`意思是文件是否存在，不是文件是否正常，建议先测试url是否能下载正常
