### ISSUE TITLE
能在统一的地方拿到所有下载任务的成功的回调吗

### ISSUE THREAD

**Issue by MQL9011** [Danie1s/Tiercel#56]
我在A页面添加一个下载, 在B页面又添加一个下载, 在C页面也添加一个下载.

我可以在某一处统一的拿到所有下载成功后的回调吗?

**Comment by Danie1s** [comment]
当然可以，因为初始化的时候就是全局的

**Comment by MQL9011** [comment]
@Danie1s   

我是这么写的,但是却没有回调啊

![image](https://user-images.githubusercontent.com/11871158/60649940-abab4000-9e75-11e9-8842-5601240088fe.png)

**Comment by Danie1s** [comment]
直接这样

```Swfit
sessionManager.success { (_) in

}
```

**Comment by MQL9011** [comment]
@Danie1s 
不行哦, 我在不同的页面批量添加下载几十条, 结果只有几个成功的回调.

**Comment by Danie1s** [comment]
是可以的，要用打印来测试
```
task.success { (_) in

}
```
