### ISSUE TITLE
下载总大小异常

### ISSUE THREAD

**Issue by wj610671226** [Danie1s/Tiercel#57]
下载demo查看下载功能，单个文件下载，将url替换成本地的，下载正常，但是task.progress.totalUnitCount = -1

**Comment by Danie1s** [comment]
可以提供一下url吗？

**Comment by wj610671226** [comment]
lazy var URLString = "http://dldir1.qq.com/qqfile/QQforMac/QQ_V4.2.4.dmg"
改为
lazy var URLString = "http://localhost/123.dmg"
打印
task.progress.totalUnitCount = -1

**Comment by Danie1s** [comment]
下载文件的大小是读取响应头里`Content-Length`字段的值，你看看有没有设置

**Comment by ZClee128** [comment]
> 下载文件的大小是读取响应头里`Content-Length`字段的值，你看看有没有设置



> 下载文件的大小是读取响应头里`Content-Length`字段的值，你看看有没有设置

https://yxd-app-dev.yuxuandao.com/knowledge/book/aa08dadec5c1468190d073d720b2d4b9.txt 我是这个链接也没有获取到，是在阿里云上的

**Comment by ZClee128** [comment]
> > 下载文件的大小是读取响应头里`Content-Length`字段的值，你看看有没有设置
> 
> > 下载文件的大小是读取响应头里`Content-Length`字段的值，你看看有没有设置
> 
> https://yxd-app-dev.yuxuandao.com/knowledge/book/aa08dadec5c1468190d073d720b2d4b9.txt 我是这个链接也没有获取到，是在阿里云上的

同一个链接，安卓是可以拿到大小的，我觉得这里面肯定有问题的

**Comment by ZClee128** [comment]
> Content-Length

作为一个开源框架，应该要适配一下不同链接，安卓的下载框架可以做到，为什么你的框架就一定要通过Content-Length这个来获取呢，不能因为用你这个框架就要改变公司策略吧

**Comment by ZClee128** [comment]
这里的确没有 Content-Length 字段，所以没有直接的文件大小信息。不过，有 Accept-Ranges: bytes 字段，这意味着该服务器支持 Range 请求（即可以进行分段下载）。
我通过以下方法
`/// 获取文件大小
    func getFileSize(from url: String, completion: @escaping (Int64?) -> Void) {
        guard let url = URL(string: url) else {
            completion(nil)
            return
        }
        var request = URLRequest(url: url)
        request.setValue("bytes=0-0", forHTTPHeaderField: "Range")
        
        let task = URLSession.shared.dataTask(with: request) { (_, response, error) in
            if let error = error {
                Logger.print("请求失败: \(error.localizedDescription)")
                completion(nil)
                return
            }
            
            guard let httpResponse = response as? HTTPURLResponse,
                  let contentRange = httpResponse.allHeaderFields["Content-Range"] as? String else {
                Logger.print("无法获取 Content-Range")
                completion(nil)
                return
            }
            
            let parts = contentRange.split(separator: "/")
            if parts.count == 2, let totalBytes = Int64(parts[1]) {
                completion(totalBytes)
            } else {
                completion(nil)
            }
        }
        task.resume()
    }`
然后我再调用你的下载，progress回调里修改数值，可以做到
