### ISSUE TITLE
断点续传过程中请求头的问题

### ISSUE THREAD

**Issue by zqgogo** [Danie1s/Tiercel#59]
你好，在使用这个框架的过程中，遇到两个问题，想请教一下怎么解决？
1.因为我们的app有切换用户这个功能，在使用断点续传的过程中，发现切换了账户后，就无法把暂停的任务继续下载了，会直接完成，但是文件没有下载完，所以导致打不开。调试之后发现原因，因为我这边的验证用户是在http头里带一个token字段进行验证的，所以暂停的ResumeData里存放的还是上次的token，而不是新的token，所以在再次登录之后，继续下载任务时，会被身份验证的拦截掉，导致下载失败。我尝试设置了下载任务的head，但结果还是一样，并没有影响，请问这种情况该怎么解决呢？
2.还有一个问题就是，我这边的下载接口在正常的时候会走正常的下载流程，但是出错的时候，比如文件没找到，或者像上面那样身份验证失败的时候，会直接返回一个json，http状态码是200，这种时候没办法获取到相关错误信息，也会直接完成掉，而文件打不开。请问有没有什么办法可以接收到这种错误信息吗？

**Comment by Danie1s** [comment]
不好意思，忘记回复了。其实两个问题的解决办法很简单，叫你们后端改。
1，既然需要身份验证，那么你切换用户的时候身份都改了，当然无法继续上次的下载。
2，出错的时候别返回200

**Comment by zqgogo** [comment]
非常感谢你上次的回答！

1.这几天又尝试了下，对于之前的第一个问题，在网上找到一个方法，就是在继续下载之前，把之前缓存的data获取出来，然后对于里面的字段进行修改，再进行继续下载。不过在目前的框架里并没有能够获取resumeData的api，如果可以的话，希望可以在之后的版本里可以提供这个接口，在继续下载之前能够有机会获得resumeData，以便有更新一些数据的机会。

2.对于第二个问题按照你所说的去做了，我让后台返回了一个自定义的http错误码，可是下载过程却出了问题，比如我故意将文件名改错，后台会拦截到这个错误并抛出对应的http错误码，但是app端的下载并没有收到，有时候它会一直处于下载中的状态，有时候又会在过一会之后直接完成掉。把下载链接直接在浏览器中请求的话，结果又没问题，是会报对应的错误码。断点调试也没发现什么问题，都正常走到startToDownload方法里面，这个方法也正常的走完了，请问这个情况该怎么解决呢？

**Comment by zqgogo** [comment]
> 不好意思，忘记回复了。其实两个问题的解决办法很简单，叫你们后端改。
> 1，既然需要身份验证，那么你切换用户的时候身份都改了，当然无法继续上次的下载。
> 2，出错的时候别返回200

非常感谢你上次的回答！

1.这几天又尝试了下，对于之前的第一个问题，在网上找到一个方法，就是在继续下载之前，把之前缓存的data获取出来，然后对于里面的字段进行修改，再进行继续下载。不过在目前的框架里并没有能够获取resumeData的api，如果可以的话，希望可以在之后的版本里可以提供这个接口，在继续下载之前能够有机会获得resumeData，以便有更新一些数据的机会。

2.对于第二个问题按照你所说的去做了，我让后台返回了一个自定义的http错误码，可是下载过程却出了问题，比如我故意将文件名改错，后台会拦截到这个错误并抛出对应的http错误码，但是app端的下载并没有收到，有时候它会一直处于下载中的状态，有时候又会在过一会之后直接完成掉。把下载链接直接在浏览器中请求的话，结果又没问题，是会报对应的错误码。断点调试也没发现什么问题，都正常走到startToDownload方法里面，这个方法也正常的走完了，请问这个情况该怎么解决呢？

**Comment by Danie1s** [comment]
我个人对于iOS开发的理解是，苹果提供了什么，你就在它基础上进行相应的开发，而不要去修改它，或者自己去弄一套新的东西，除非你很有空或者迫不得已。因为苹果是十分封闭的，你自行修它提供的东西，随时会发生问题，或者它有些机制会随时改变，只要它一改变，你之前那些努力都白费。

1. 我之前就看到，好像从iOS 11开始，如果修改resumeData，会发生错误
2. 尝试返回常用的http错误码，400开头，或者500开头的

我说一下我的思路：
1. 不要在下载过程中去验证，而是在请求第一个字节的时候进行验证，如果验证通过，则后面不再验证，这样就可以保证怎么切换用户都不会有问题。
2. 你不想别的用户可以下载之前用户的东西，可以根据用户标识来判断是否显示之前的下载任务
3. 对于URLSessionDownloadTask，苹果的意思就是，提供了断点续传，但这个任务是不可以修改的，只能在原来的任务继续，所以我不建议你去想办法修改这个任务

**Comment by zqgogo** [comment]
> 我个人对于iOS开发的理解是，苹果提供了什么，你就在它基础上进行相应的开发，而不要去修改它，或者自己去弄一套新的东西，除非你很有空或者迫不得已。因为苹果是十分封闭的，你自行修它提供的东西，随时会发生问题，或者它有些机制会随时改变，只要它一改变，你之前那些努力都白费。
> 
> 1. 我之前就看到，好像从iOS 11开始，如果修改resumeData，会发生错误
> 2. 尝试返回常用的http错误码，400开头，或者500开头的
> 
> 我说一下我的思路：
> 
> 1. 不要在下载过程中去验证，而是在请求第一个字节的时候进行验证，如果验证通过，则后面不再验证，这样就可以保证怎么切换用户都不会有问题。
> 2. 你不想别的用户可以下载之前用户的东西，可以根据用户标识来判断是否显示之前的下载任务
> 3. 对于URLSessionDownloadTask，苹果的意思就是，提供了断点续传，但这个任务是不可以修改的，只能在原来的任务继续，所以我不建议你去想办法修改这个任务

好的，我明白你的意思了，谢谢你的回复！那我再尝试一下尽量不去修改的方法看看，错误码我也试一下，谢啦！
