### ISSUE TITLE
断开网的时候不会有错误回调

### ISSUE THREAD

**Issue by HevenHoo** [Danie1s/Tiercel#60]

**Comment by HevenHoo** [comment]
如果断开网了，然后暂停任务再开始下载任务就会使已经下载的临时文件丢失掉，后面即使连网了再继续下载也下不了

**Comment by Danie1s** [comment]
1. 如果任务开始后，网络断开，任务不会中断，而是进入暂停状态，直到网络连接上后会自动继续下载。
2. 而如果你断网的时候调用task的`suspend()`方法，其实底层是会把任务取消，这时候跟网络就没有任何关系了，无论什么状态都可以恢复任务，只不过没有网络的时候不能开始而已。
3. 至于你说的临时文件丢失掉，是因为你使用Xcode进行调试，每次运行App的时候，沙盒路径是会改变的
4. 但我个人建议是，自己集成一个检测网络的库，Alamofire就有提供，断网的时候手动暂停任务，因为我不确定`1`那种情况可以暂停多久
