### ISSUE TITLE
iOS12.2 暂停->开始，续传进度丢失，重新开始下载

### ISSUE THREAD

**Issue by zhushengxiong** [Danie1s/Tiercel#62]
下载网易云音乐的地址http://d1.music.126.net/dmusic/d5a7/2019618171016/NeteaseMusic_2.1.1_790_web.dmg
在iOS12.2环境中，下载单个文件，下载一段时间之后暂停，再点开始变成重新开始来，而不是断点续传的，是不是iOS12.2的resumeData格式又发生了变化

**Comment by Danie1s** [comment]
我测试了一下，只有这个url有问题，具体是什么原因，还需要时间确定，估计是`URLSessionDownloadTask`不支持

**Comment by zhushengxiong** [comment]
嗯，我也发现了，用了你demo中的其他url都没问题

**Comment by leeCoding** [comment]
我测试了下载发现我们公司的服务器下的资源都是这种情况，这两个方法 cancelByProducingResumeData 和 didCompleteWithError 里面的取的resumedata都为nil，不知道是什么原因，系统都是在iOS 12+

**Comment by Danie1s** [comment]
@leeCoding 可以提供一下url吗

**Comment by leeCoding** [comment]
@Danie1s  http://d30.xcenable.com/storage/attachment/2019/8/14/4f9516f08b134a0c81a7c68247580a0f.mp4 用这个试一下

**Comment by Danie1s** [comment]
我觉得是服务器设置问题，你们可以用Safari试试，因为Safari也是用`URLSessionDownloadTask`实现的，结果也是一样。你们可以叫公司的后端对比一下那些正常断点续传的url，看看区别，试一下能不能修复

**Comment by leeCoding** [comment]
如果是服务器的原因会是什么原因，我用curl -I 对比了下出问题的url请求头 
有问题url
<img width="744" alt="image" src="https://user-images.githubusercontent.com/12134648/64671928-8f8ed500-d49c-11e9-8646-309dc3b1b54a.png">
无问题url
<img width="754" alt="image" src="https://user-images.githubusercontent.com/12134648/64671977-bb11bf80-d49c-11e9-81d3-7d33926724f4.png">
发现好像并没有什么不同，服务器应该都是支持断点续传的，Safari 下载有问题，Google 下载无问题

**Comment by leeCoding** [comment]
如果是服务器的原因会是什么原因，我用curl -I 对比了下出问题的url请求头
有问题url
<img width="750" alt="image" src="https://user-images.githubusercontent.com/12134648/64672158-40956f80-d49d-11e9-93ab-fdf436ea67e4.png">

无问题url
<img width="732" alt="image" src="https://user-images.githubusercontent.com/12134648/64672175-4ab76e00-d49d-11e9-8816-2ead02595efa.png">

发现好像并没有什么不同，服务器应该都是支持断点续传的，Safari 下载有问题，Google 下载无问题

**Comment by Danie1s** [comment]
Safari肯定是用自家的API实现的，Chrome等第三方就不一样。至于到底问题出在哪里，我目前也不清楚

**Comment by Danie1s** [comment]
@leeCoding 
hi，我估计问题是在于你们服务器没有添加这个响应头：Content-Type: application/octet-stream
你可以叫你们同事加上试试

**Comment by leeCoding** [comment]
感谢，我们试一下--    发自新浪邮箱客户端
在 11月16日 11:39，Danie1s <notifications@github.com> 写道：
@leeCoding


hi，我估计问题是在于你们服务器没有添加这个响应头：Content-Type: application/octet-stream


你可以叫你们同事加上试试



&mdash;

**Comment by Danie1s** [comment]
还有服务器端需要支持ETag或者是Last－Modified

**Comment by leeCoding** [comment]
我们这边尝试加上了，似乎并不能解决问题，你那边还有什么建议吗？
----- 原始邮件 -----
发件人：Danie1s <notifications@github.com>
收件人：Danie1s/Tiercel <Tiercel@noreply.github.com>
抄送人：Jonny_Li <nscode@sina.com>,  Mention <mention@noreply.github.com>
主题：Re:_[Danie1s/Tiercel]_iOS12.2_暂停->开始，续传进度丢失，重新开始下载_(#62)
日期：2019年11月16日 11点49分

还有服务器端需要支持ETag或者是Last－Modified



&mdash;

**Comment by Danie1s** [comment]
那我也不知道了，你还是跟其他url对比一下吧
