### ISSUE TITLE
老哥，别改API了😭

### ISSUE THREAD

**Issue by ripperhe** [Danie1s/Tiercel#64]

**Comment by Danie1s** [comment]
请问哪里出现问题了，总体改动还是很小的吧？

**Comment by ripperhe** [comment]
其实还好啦，问题主要是有次更新你把 URLString 改成了 url.absoluteString，导致项目报错了
建议在修改公用 API，并且不向下兼容的时候，修改主版本号
https://semver.org/lang/zh-CN/
