### ISSUE TITLE
是否考虑把原始的URLSessionDownloadTask暴露出来？

### ISSUE THREAD

**Issue by FlyKite** [Danie1s/Tiercel#65]
目前项目里要下载的文件有可能会有403或404等其他情况，服务器报403时didCompleteWithError代理方法里的error为nil，目前Tiercel纯粹当成成功来处理了并且没有任何方式获取到HTTP状态码。
我们项目里如果下载一个文件的时候HTTP状态码是403的话需要请求接口去获取新的下载链接，目前因为无法获取到HTTP状态码，只能用下载的文件大小小于XXX来判断。

**Comment by Danie1s** [comment]
可以提供测试的url吗？会出现403的url

**Comment by FlyKite** [comment]
https://video.wumii.tv/sv/4f4b3f33-16776a608cb/4f4b3f33-16776a608cb.mp4?auth_key=1234

**Comment by FlyKite** [comment]
func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?)
结束后代理方法里的error为nil，因此Tiercel当做成功来处理了，但实际上HTTP状态码为403，这个下载成功是把403 Forbidden那个页面给下载下来了。

**Comment by Danie1s** [comment]
恩，我明白了，error不会报告这些错误，`URLSessionDownloadTask`也不会因为这些错误变成失败，而是照常下载了，这是苹果的设计，你可以试试用Safari打开这个url，结果是一样的，这证明了苹果的理念，默认遇到媒体类型的url就会直接下载。

我明白你们的需求，是想在url里加上校验，校验通过才开始下载。这种需求其实更加适合用`URLSessionDataTask`来实现，在`urlSession(_:dataTask:didReceive:completionHandler:)`中拦截，而`URLSessionDownloadTask`则不会调用该代理方法，所以无法在下载前进行判断。

Tiercel是下载库，专注于下载，而且需要实现后台下载功能，必须要用`URLSessionDownloadTask`。

当然也可以在`urlSession(_:task:didCompleteWithError:)`通过response来进行判断，但这样带来的效果就是，文件已经下载了，好像跟这个需求的原意相离了。

我会找个时间更新一下，把这种错误也考虑进去。但是我建议把验证和下载分开，先验证完，拿到可以下载的url直接下载，这样会比较符合苹果的理念，并且会避免断点续传时的问题

**Comment by FlyKite** [comment]
OK, Thanks.
主要是服务端没有给出校验用的MD5或者SHA1，让我们用HTTP状态码来判断，所以希望能将原始的URLSessionDownloadTask暴露出来，这样我们就可以处理这种意外情况了。

**Comment by Danie1s** [comment]
我想问一个问题，这个url可以断点续传吗？你有试过下载过程中暂停，然后再继续吗

**Comment by FlyKite** [comment]
在HTTP状态码不是403的时候是可以的，支持断点续传，至于403的时候只有254字节，完成得太快了根本没法测试这254字节是否支持断点续传。

**Comment by Danie1s** [comment]
ok

**Comment by kyunooo** [comment]
同样情况，下载链接过期无法处理。

**Comment by Danie1s** [comment]
@FlyKite @kyunooo 麻烦更新到 2.4.0，进行测试
