### ISSUE TITLE
批量下载时总进度错乱

### ISSUE THREAD

**Issue by wwx1991** [Danie1s/Tiercel#67]
如题，批量（比如二十几个小音频文件）下载时总进度错乱

**Comment by Danie1s** [comment]
原因：并发下载的数量最大为6，而下载的是二十几个小音频文件，这样就会不停的有任务下载完成，同时有新任务添加进去，导致总大小一直在改变。
解决方法：当下载任务的数量比较多的时候，使用 已完成 / 总任务 作为进度
