### ISSUE TITLE
handleEventsForBackgroundURLSession 没有调用

### ISSUE THREAD

**Issue by garryzhong** [Danie1s/Tiercel#69]
在 appdelegate 的 handleEventsForBackgroundURLSession 断点，发现没有调用，后台下载功能也没有起作用。

这个有点奇怪，系统是 iOS 13.1

**Comment by Danie1s** [comment]
在其他系统版本上有问题吗？目前还没有发布支持 iOS 13.1 的正式版Xcode，等发布后我再测试

**Comment by Danie1s** [comment]
Xcode已经更新，我刚测试了，系统是iOS 13.1.2，没有问题

**Comment by garryzhong** [comment]
好的，我也升级到13.1.2了，发现可以后台下载了。
大哥辛苦了辛苦了。
