### ISSUE TITLE
使用 suggestedFilename， 而不是路径最后一段.

### ISSUE THREAD

**Issue by aidevjoe** [Danie1s/Tiercel#7]
**如果自己不指定文件名，应该使用 suggestedFilename**

比如我通过此链接下载仓库
https://codeload.github.com/Danie1s/Tiercel/zip/master

如果不指定文件名，默认都是路径最后一段，类似在GitHub 下载源码，文件名将全部成为 master， 并且不能很方便到指定它是什么类型(zip)。

**Comment by Danie1s** [comment]
谢谢你给我的建议，你说的非常有道理，在刚开始设计这个框架的时候，我也考虑过。suggestedFilename是在task开始以后，接受到session回调后才能得到，包括电脑上使用的迅雷等下载软件其实也是访问了链接以后才返回一个对话框让用户进行设置。而Tiercel在task开始之前已经做了一些跟文件相关的处理和判断（主要是缓存方面），所以我为了方便，用了URL的最后一段作为默认的文件名，这样也可以配合cache里面的方法（根据URLString获得下载文件的路径），考虑到app里面下载的链接大部分都是最后一段可以做为文件名，所以我就这样写了。关于这个问题，我会尝试进行修改，如果你还有什么好的想法，欢迎提出。

**Comment by Danie1s** [comment]
为了可以直接用url检索到对应的本地文件，所以我没有使用suggestedFilename，现在已经更新到Tiercel 2，默认使用url的md5加上文件扩展名

**Comment by FlyerYe** [comment]
请问如何通过URLSrting获取这个文件名并拿到地址

**Comment by Danie1s** [comment]
`cache.filePath(url:)`
