### ISSUE TITLE
SessionManager对单个任务的状态是否可以提供回调

### ISSUE THREAD

**Issue by coldmn3** [Danie1s/Tiercel#70]
比如可以用SessionManager全局监控  单个文件的成功、失败等

**Comment by Danie1s** [comment]
SessionManager通过url就可以获取对应的task，task里面就有回调

**Comment by coldmn3** [comment]
你好，不好意思，可能没表达清楚

我需要在一个下载任务完成后进行相应的操作（如改名，保存到相册等额外操作），此时我不知道是哪个任务完成了，也没有url。需要 SessionManager提供类似 .singleTaskComplete 这种回调。目前SessionManager只有所有文件下载完后success的回调，没找到单个文件下载完成的回调

**Comment by Danie1s** [comment]
你需要的是类似于`通知`这种功能吧，不好意思目前没有实现这个

你可以在task的回调里发送`通知`

**Comment by coldmn3** [comment]
好的，谢谢，了解了。再次感谢
