### ISSUE TITLE
totalRemove停止所有视频的下载，下次再下载时，进度会有多个回调

### ISSUE THREAD

**Issue by xujiayong** [Danie1s/Tiercel#71]
项目需求是，退出页面，停止视频的下载，所以我调用的manager.totalRemove()方法。但是下次再进入此页面，开始下载一个视频时，发现进度回调会有多个。也就是之前曾下载了一部分的那个回调。导致页面上进度条显示一会儿多一会儿少。请问是哪里出了问题呢？

**Comment by xujiayong** [comment]
不是多个视频的进度回调乱蹿了，而是同一个视频，我只下载了一个视频。下了一部分，停止下载。下次再来下载这个视频。进度回调有两个。回调里面的URL也显示确实是同一个URL，所以确定就是有两个进度回调

**Comment by Danie1s** [comment]
你可以用demo进行尝试吗？

**Comment by xujiayong** [comment]
感谢回复。还没有demo。我弄一个吧
另外。SessionManager也是只有唯一的一个。APPDelegate里面持有的

**Comment by Danie1s** [comment]
你把url放在我项目里的demo试试

**Comment by xujiayong** [comment]
好的，我试试

**Comment by xujiayong** [comment]
> 你把url放在我项目里的demo试试

放你的demo里面是没问题的 *_*    那我再看看吧。谢谢
