### ISSUE TITLE
后台多任务串行下载特别慢，基本不可用

### ISSUE THREAD

**Issue by const-zhou** [Danie1s/Tiercel#75]
当创建多个任务后切换到后台，发现任务的下载速度贼慢。任务列表中的每个任务大小不到1MB，前台时下载大概1s一个，切后台后20分钟只能下载3个，苹果文档有说明后台唤醒的时间会越来越慢。
请问一下，大佬有在如下几个方面做尝试过吗？
1、后台唤醒后重新创建一个nsurlsession？
2、每次唤醒后申请后台任务时间？
3、优化handleEventsForBackgroundURLSession返回中的completionHandler的调用时机？

**Comment by Danie1s** [comment]
既然你有看过苹果相关的文档，那么你也应该清楚苹果这样设计的原因。

你说的这个3个方法应该都不能解决这个问题，但就算是解决了，随之而来的是耗电的增加，还有后续维护难度的增加。如果你实在是想在后台下载大量文件，建议把这些文件压缩成一个包。

**Comment by const-zhou** [comment]
@Danie1s 我试了一下https://github.com/onezens/YCDownloadSession 这个库。我也看到你在18年有说他的库有问题？我这边测试的时候他的demo在后台超过20分钟都未被杀掉。他申请了后台执行，在要被杀掉的时候才调用completionHandler，且创建新的nsurlsession。我想请问一下大佬对这块怎么看，或者说有什么坑？

**Comment by const-zhou** [comment]
另外提一个小建议，库中包含了一个类名SessionManager，和alamofire中的类名相同。可以考虑给库中类名加统一前缀

**Comment by Danie1s** [comment]
后台下载这块之前确实很少人做得比较好，我一开始也有很多不懂的地方，所以也去参考了别人的代码，那时候有测他的demo，发现存在问题，但现在已经忘记了。

我刚去看了一下，他没有申请后台时间，而是一直在计时，当app快要被暂停才调用completionHandler，并且又取消没有下载完成的任务，重新创建session，我个人认为这是没必要的。

iOS 确实有提供申请后台时间的API，但是这不是用于后台下载的，这样做应该会存在隐患，还是遵循官方推荐的做法最好。

关于类名问题，带前缀名是OC的风格，而Swift有命名空间，所以不需要加前缀
