### ISSUE TITLE
我们工程用的OC，所以写了几个桥接类支持OC，有需求的同学可以找我(不知作者是否同意)。目的只有一个，增强作者框架的健壮性，可以让更多OC的开发者使用

### ISSUE THREAD

**Issue by zhuangtao97** [Danie1s/Tiercel#76]

**Comment by swlfigo** [comment]
可否贴出地址参考下~谢谢

**Comment by Danie1s** [comment]
没问题。如果可以的话，PR一下，我有空会合并

**Comment by zhuangtao97** [comment]
> 没问题。如果可以的话，PR一下，我有空会合并

没问题的，最近比较忙。我周末抽空提一下。

**Comment by zhuangtao97** [comment]
> 可否贴出地址参考下~谢谢

我周末PR一下，能等等吗？我并没有上传都任何平台。

**Comment by swlfigo** [comment]
@zhuangtao97  哈哈好的~感谢

**Comment by zhuangtao97** [comment]
> @zhuangtao97 哈哈好的~感谢

fork后的地址：(https://github.com/zhuangtao97/Tiercel.git) 里面包含了demo

**Comment by swlfigo** [comment]
@zhuangtao97   
👍 感谢,最近要重构项目下载模块,历史与项目问题VC不能用Swift混编,正愁 Task 与 SessionManager 如何桥接使用.希望作者查看代码没问题的话合并下,OC项目的福音😁
@Danie1s

**Comment by Danie1s** [comment]
@zhuangtao97 感谢这位老铁提供的代码，我看了一下，这种桥接确实是十分方便，但我个人不太喜欢这种做法，因为这是个Swift的项目，不太希望有一些OC的东西掺杂进去，或许可以把OC的桥接部分做成另外一个库，当做插件。我目前没有时间去处理这个项目，有需要的朋友可以使用这位老铁提供的代码

**Comment by Danie1s** [comment]
@zhuangtao97 @swlfigo 
我写了一个桥接的扩展， [TiercelObjCBridge](https://github.com/Danie1s/TiercelObjCBridge) 
欢迎使用测试
