### ISSUE TITLE
下载的时候不停点击暂停继续，会丢失下载好的数据

### ISSUE THREAD

**Issue by jackCaptian** [Danie1s/Tiercel#78]
http://video1.muguace.com/yzm_video/20191004/fsFUvrLJ/mp4/fsFUvrLJ.mp4

**Comment by jackCaptian** [comment]
大神你好，能帮我看看是不是后台的问题吗，后台说支持断点，但是总是请求很慢

**Comment by Danie1s** [comment]
我测试了没问题，你可以用demo测试一下
