### ISSUE TITLE
下载完后，把文件删除，再次下载会直接走成功回调，实际没有再次去下载文件

### ISSUE THREAD

**Issue by TisonCai** [Danie1s/Tiercel#79]
看到SessionManager持有的tasks数组会保存已经下载的DownloadTask，每次去下载会先在fetchTask判断，如果有tasks匹配且status为成功状态，就直接走成功回调了，实际上文件没有下载到

**Comment by Danie1s** [comment]
是的，这个逻辑存在优化的地方，目前的建议是：用Tiercel下载的文件，用Tiercel管理，就是你删除文件后，需要把任务也删除

**Comment by TisonCai** [comment]
👌谢谢回复，目前的做法是删除文件的同时调用didCancelOrRemove也把task删除

**Comment by Danie1s** [comment]
SessionManager 的remove方法可以删除任务，同时把文件也删除

**Comment by Resoulte** [comment]
> SessionManager 的remove方法可以删除任务，同时把文件也删除

在iOS12上不好使，仍然不会重新下载

**Comment by wenhaoChan** [comment]
> 

我也遇到类似的问题,请问你解决了吗

**Comment by wenhaoChan** [comment]
> > SessionManager 的remove方法可以删除任务，同时把文件也删除
> 
> 在iOS12上不好使，仍然不会重新下载

> >  我也遇到同样的问题，请问你有解决了吗？

**Comment by wenhaoChan** [comment]
> > SessionManager 的remove方法可以删除任务，同时把文件也删除
> 
> 在iOS12上不好使，仍然不会重新下载

我也遇到同样的问题，请问你有解决了吗？
