### ISSUE TITLE
swift

### ISSUE THREAD

**Issue by guojingjingghost** [Danie1s/Tiercel#81]

**Comment by guojingjingghost** [comment]
swift 4   downloadManger.download(url)?.progress(onMainQueue: true, { (task) in
            print(task.progress.fractionCompleted)
        })这个回调没走是不是最新版本不支持 请问swift 4 应该用哪个版本

**Comment by Danie1s** [comment]
你这个问题应该不是版本问题，最好检查一下代码
另外，Swift 4和Swift 5差别不大，建议更新到最新的Swift版本，使用最新的Tiercel
