### ISSUE TITLE
你好库非常好，有个问题

### ISSUE THREAD

**Issue by guojingjingghost** [Danie1s/Tiercel#82]
请问我想全局监听每个下载文件的状态，不是在当前下载界面监听，以便后期所有文件统一管理,请问我该怎么监听呢，

**Comment by Danie1s** [comment]
麻烦参考Demo

**Comment by guojingjingghost** [comment]
demo里并没有啊比如我有这样的需求我下载了一堆文件，我怎么能方便的取出现在正在下载的哪个文件呢

**Comment by Danie1s** [comment]
兄弟，你是新手吗？你设置为`AppDelegate `的属性，不就可以全局拿到了吗？`sessionManager.tasks.first { $0.status == .running }`不就可以取出现在正在下载的任务了吗？

**Comment by guojingjingghost** [comment]
谢谢了
