### ISSUE TITLE
下载成功，目标文件却不存在

### ISSUE THREAD

**Issue by wuchun4** [Danie1s/Tiercel#83]
任务下载完成并有回调，但是偶尔会出现检测目标文件却不存在
}).success(onMainQueue: true, {[weak self] (task) in //

            guard let strong = self else{
                return
            }
            var haveError = false
            let path = task.filePath
            if FileManager.default.fileExists(atPath: path) == false{
                haveError = true
            }

**Comment by Danie1s** [comment]
你可以先在demo里面多试几次吗？

**Comment by wuchun4** [comment]
谢谢回复这个问题。发现 和 #79 是类似的，成功下载一次，如果文件丢失，再次下载成功回调，其实并没有下载，只能在下载前主动调用删除任务，这样的话，导致预先下载的缓存都没了，又要重新开始，希望优化这个问题，就是重复下载数据前先判断一下文件是否存在，再决定任务的状态，不要只是根据字段设置为成功就直接成功回调任务。这样的话就保证去除了一些假成功的存在，希望改进，谢谢~

**Comment by Danie1s** [comment]
你这里的说法很矛盾，既然文件丢失了，那么预先下载的缓存就肯定不存在

这个库跟现在很多软件的逻辑是一样的，如果你有下载成功过，而且任务也保留在manager的话，那肯定是标志已经下载，但实际上这个文件后续是否有存在，这个跟manager是无关的，如果你希望知道文件是否还存在，那只能进行多一次的判断。如果你想再次下载，很多软件都是需要你先把之前的任务删除

造成这个原因，一般是因为你移动或者删除了文件，但任务还保留在manager那里。建议你需要删除文件的话，使用manager的API去移除任务，可以同时把文件也删除。

后续可能我也会进行优化
