### ISSUE TITLE
可否在completed回调中拿到原始的URLSessionTask？

### ISSUE THREAD

**Issue by TisonCai** [Danie1s/Tiercel#84]
有些文件下载链接做了混淆，下载前通过lastPathComponent无法获取准确的文件名及对应的格式，需要在下载完后修改正确的文件名，观察发现会在URLResponse的suggestedFilename属性中携带，目前无法通过自定义的DownloadTask获取？

**Comment by Danie1s** [comment]
我也发现了暴露原始URLSessionTask的必要性，但还没有想好怎么设计，请耐心等待

**Comment by TisonCai** [comment]
[强][强]可能也要暴露一些修改文件名的api

**Comment by Danie1s** [comment]
@TisonCai 已经暴露一些相关属性

**Comment by TisonCai** [comment]
Thanks
