### ISSUE TITLE
批量下载问题

### ISSUE THREAD

**Issue by IVnaBo** [Danie1s/Tiercel#85]
我现在的问题是批量下载。想每下载完成一个就把图片添加到图库中。这要怎么做。怎么获取下载完成的文件。` manager.cache.fileURL(fileName: manager.fetchTask())` 怎么获取当前下载好的task.

**Comment by IVnaBo** [comment]
我看了你的批量下载。是在所有任务都完成了才回调success方法。

**Comment by Danie1s** [comment]
批量下载的方法会返回一个数组，给数组调用success方法就可以

**Comment by hstdt** [comment]
如果有缓存，创建的task是一个空数组。`.success`和`.failure`也都会因为空数组而不初始化。

**Comment by Danie1s** [comment]
sorry，新版的这里改了一下逻辑，我马上改回原来的

**Comment by Danie1s** [comment]
已经更新

**Comment by hstdt** [comment]
@Danie1s 好了，谢谢~
