### ISSUE TITLE
Tiercel框架流程图

### ISSUE THREAD

**Issue by rogertan30** [Danie1s/Tiercel#88]
我们自己的项目的下载部分，使用了这套框架。非常稳定，感谢作者。
在公司内部分享的时候，我画了这个框架的流程图。

地址：[Tiercel框架源码阅读
](https://github.com/rogertan30/GeekTime/blob/master/%E5%8D%AB%E5%A3%AB%E4%BA%91%E7%9B%98iOS%E7%AB%AF%E4%B8%8B%E8%BD%BD%E6%A1%86%E6%9E%B6%E5%9B%BE1.0%E7%89%88.png)

希望对大家理解这套框架有帮助！

**Comment by Danie1s** [comment]
兄弟，谢谢你的赏识，Tiercel 3.0 已经发布，总体逻辑没变，但性能有了极大的提高，欢迎使用
