### ISSUE TITLE
有没有全局的 文件下载完成了一个，就回调一次的方法呢

### ISSUE THREAD

**Issue by lumengru** [Danie1s/Tiercel#89]
项目在批量下载的时候，如果其中一个文件下载完成，我需要移动这个文件到其他地方，怎么才能获取到文件下载完成的方法呢，在cell赋值的时候，显然是不可以的，等全部任务下载完成也不合适，那么有没有一个，只要文件下载完成了一个，就回调一次的方法呢

**Comment by lumengru** [comment]
或者在下载的时候指定下载路径

**Comment by Danie1s** [comment]
可以对所有task设置回调
```swift
sessionManager?.tasks.success { task in
            
}
```

实际上，我也打算加上自定义路径功能

**Comment by lumengru** [comment]
好的 多谢

**Comment by lumengru** [comment]
> 可以对所有task设置回调
> 
> ```swift
> sessionManager?.tasks.success { task in
>             
> }
> ```
> 
> 实际上，我也打算加上自定义路径功能

大概什么时候可以更新呢，我在APPDelegate里面使用这个方法，并没有调用，起初我以为在新增下载的时候需要重新设置一次 这个方法，所以在下载未完成的时候 重新启动APP发现也不可以

**Comment by lumengru** [comment]
> 可以对所有task设置回调
> 
> ```swift
> sessionManager?.tasks.success { task in
>             
> }
> ```
> 
> 实际上，我也打算加上自定义路径功能

我这边的需求是，当批量下载的过程中，有一个下载成功了，就会给我一个回调，告诉我有文件下载完成了，这时候我会把缓存的文件移动到其他的文件夹下面。或者是在调用开始下载的时候，就指定文件下载完成后，文件放到哪个文件夹下面

**Comment by lumengru** [comment]
@Danie1s 大概什么时候可以更新呢，我在APPDelegate里面使用这个方法，并没有调用，起初我以为在新增下载的时候需要重新设置一次 这个方法，所以在下载未完成的时候 重新启动APP发现也不可以

**Comment by lumengru** [comment]
@Danie1s 我这边的需求是，当批量下载的过程中，有一个下载成功了，就会给我一个回调，告诉我有文件下载完成了，这时候我会把缓存的文件移动到其他的文件夹下面。或者是在调用开始下载的时候，就指定文件下载完成后，文件放到哪个文件夹下面

**Comment by Danie1s** [comment]
有回调的，只不过应该是你又对task单独设置了，所以冲突了，麻烦你检查一下自己的代码

**Comment by lumengru** [comment]
你是对的，我在赋值的时候单独设置了
