### ISSUE TITLE
tasks的下载进度如何计算

### ISSUE THREAD

**Issue by qiniu201612** [Danie1s/Tiercel#90]
大佬这个tasks的下载进度如何计算呢？
self.tasks = self.sessionManager?.multiDownload(self.downloadURLStrings)

**Comment by Danie1s** [comment]
如果你的`sessionManager`里面只有这些任务，那么可以使用`sessionManager.progress { }`

如果你的`sessionManager`里面还有其他任务，那么需要手动去计算
