### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by FlyerYe** [Danie1s/Tiercel#93]
现在有这样一种现象，如果下载的是很多图片，在tableviewcell中读取沙盒中的图片，在滑动时会很卡顿，请问有二级缓存机制吗？或者怎么能解决读取图片卡顿的问题，我尝试了在cell中开启子线程，还是会卡顿。

**Comment by Danie1s** [comment]
这是另外一个问题，如果是要加载图片的话，推荐用`Kingfisher`
