### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by FlyerYe** [Danie1s/Tiercel#94]
当下载数量过大时，暂停后重新调用totalstart,会内存增加而闪退
![image](https://user-images.githubusercontent.com/15828484/75036387-b42bb600-54ec-11ea-968b-7d8852cde9a5.png)

**Comment by Danie1s** [comment]
抱歉，我没有找到这么多url，可以提供一下这些urls吗？

**Comment by FlyerYe** [comment]
[url.zip](https://github.com/Danie1s/Tiercel/files/4236293/url.zip)

**Comment by Danie1s** [comment]
感谢你提出的问题和urls，我已经知道怎么优化，但是需要更多的测试调整，这两天会更新

**Comment by FlyerYe** [comment]
好的，谢谢你。

**Comment by FlyerYe** [comment]
还有就是开始，暂停，删除切换的时候经常会卡住，有什么好的方法吗

**Comment by Danie1s** [comment]
已经更新，进行了大量优化
