### ISSUE TITLE
swift 4.2就不能用了么？无语

### ISSUE THREAD

**Issue by Alvazz** [Danie1s/Tiercel#98]

**Comment by Danie1s** [comment]
Swift 5 跟Swift 4.2 差别不大，你可以更新代码或者使用旧版的 Tiercel

**Comment by Alvazz** [comment]
可是我们的项目是4.2的，直接pod install进去，一顿懵逼，各种爆红

**Comment by Alvazz** [comment]
3.0支持吗？我用的是3.2？哪个版本支持4.2啊？
